// 전 세계 다이빙 스팟 데이터
export const REGIONS = [
  { id: 'korea', label: '한국', labelEn: 'Korea' },
  { id: 'southeast-asia', label: '동남아시아', labelEn: 'Southeast Asia' },
  { id: 'oceania', label: '오세아니아', labelEn: 'Oceania' },
  { id: 'indian-ocean', label: '인도양', labelEn: 'Indian Ocean' },
  { id: 'red-sea', label: '홍해', labelEn: 'Red Sea' },
  { id: 'caribbean', label: '카리브해', labelEn: 'Caribbean' },
  { id: 'europe', label: '유럽', labelEn: 'Europe' },
  { id: 'east-asia', label: '동아시아', labelEn: 'East Asia' },
  { id: 'pacific', label: '태평양', labelEn: 'Pacific' },
];

export const DIFFICULTIES = [
  { id: 'beginner', label: '초급', labelEn: 'Beginner', color: '#22c55e' },
  { id: 'intermediate', label: '중급', labelEn: 'Intermediate', color: '#f59e0b' },
  { id: 'advanced', label: '상급', labelEn: 'Advanced', color: '#ef4444' },
];

export const ACTIVITY_TYPES = [
  { id: 'skin', label: '스킨(스노클링/프리다이빙)', labelEn: 'Skin (Snorkeling/Freediving)' },
  { id: 'scuba', label: '스쿠버다이빙', labelEn: 'Scuba Diving' },
];

export const COUNTRY_MAP = [
  { ko: '한국', en: 'South Korea' },
  { ko: '필리핀', en: 'Philippines' },
  { ko: '태국', en: 'Thailand' },
  { ko: '인도네시아', en: 'Indonesia' },
  { ko: '말레이시아', en: 'Malaysia' },
  { ko: '팔라우', en: 'Palau' },
  { ko: '호주', en: 'Australia' },
  { ko: '프랑스령 폴리네시아', en: 'French Polynesia' },
  { ko: '뉴질랜드', en: 'New Zealand' },
  { ko: '피지', en: 'Fiji' },
  { ko: '몰디브', en: 'Maldives' },
  { ko: '세이셸', en: 'Seychelles' },
  { ko: '탄자니아', en: 'Tanzania' },
  { ko: '프랑스령 레위니옹', en: 'Reunion' },
  { ko: '이집트', en: 'Egypt' },
  { ko: '멕시코', en: 'Mexico' },
  { ko: '벨리즈', en: 'Belize' },
  { ko: '네덜란드령 안틸레스', en: 'Netherlands Antilles' },
  { ko: '케이맨 제도', en: 'Cayman Islands' },
  { ko: '포르투갈', en: 'Portugal' },
  { ko: '몰타', en: 'Malta' },
  { ko: '크로아티아', en: 'Croatia' },
  { ko: '노르웨이', en: 'Norway' },
  { ko: '일본', en: 'Japan' },
  { ko: '대만', en: 'Taiwan' },
  { ko: '에콰도르', en: 'Ecuador' },
  { ko: '미크로네시아', en: 'Micronesia' },
  { ko: '통가', en: 'Tonga' },
  { ko: '코스타리카', en: 'Costa Rica' },
  { ko: '콜롬비아', en: 'Colombia' },
  { ko: '바하마', en: 'Bahamas' },
  { ko: '온두라스', en: 'Honduras' },
  { ko: '아이슬란드', en: 'Iceland' },
  { ko: '남아프리카공화국', en: 'South Africa' },
];

export const spots = [
  // ── 한국 (7곳) ──
  {
    id: 1,
    name: '문섬',
    region: 'korea',
    country: '한국',
    lat: 33.2270,
    lng: 126.5650,
    depth: '5~40m',
    visibility: '10~30m',
    waterTemp: { min: 14, max: 26 },
    difficulty: 'intermediate',
    bestSeason: ['6월', '7월', '8월', '9월', '10월'],
    marineLife: ['연산호', '해마', '쏠배감펭', '넙치', '문어'],
    description: '제주도 서귀포 앞바다에 위치한 무인도로, 국내 최고의 연산호 군락지입니다. 화려한 수중 경관과 다양한 해양생물을 만날 수 있습니다.',
    highlights: ['국내 최대 연산호 군락', '수중 절벽 월다이빙', '다양한 난류성 어종'],
    countryEn: 'South Korea',
    nameEn: 'Munseom',
    descriptionEn: 'An uninhabited island off Seogwipo, Jeju, home to Korea\'s finest soft coral colonies. Enjoy stunning underwater scenery and diverse marine life.',
    highlightsEn: ['Korea\'s largest soft coral colony', 'Wall diving along underwater cliffs', 'Diverse warm-current fish species'],
    marineLifeEn: ['Soft coral', 'Seahorse', 'Lionfish', 'Flounder', 'Octopus'],
    activityTypes: ['skin', 'scuba'],
  },
  {
    id: 2,
    name: '우도',
    region: 'korea',
    country: '한국',
    lat: 33.5040,
    lng: 126.9520,
    depth: '5~25m',
    visibility: '8~20m',
    waterTemp: { min: 13, max: 25 },
    difficulty: 'beginner',
    bestSeason: ['6월', '7월', '8월', '9월'],
    marineLife: ['돌돔', '자리돔', '해삼', '성게', '소라'],
    description: '제주도 동쪽에 위치한 우도는 초보 다이버에게 적합한 완만한 수중 지형을 가지고 있으며, 맑은 물과 아름다운 백사장이 특징입니다.',
    highlights: ['초보자 친화적 포인트', '백사장 모래바닥', '완만한 수중 지형'],
    countryEn: 'South Korea',
    nameEn: 'Udo',
    descriptionEn: 'Located east of Jeju, Udo offers gentle underwater terrain ideal for beginners, featuring crystal-clear water and beautiful white sand beaches.',
    highlightsEn: ['Beginner-friendly points', 'White sand bottom', 'Gentle underwater terrain'],
    marineLifeEn: ['Rock bream', 'Damselfish', 'Sea cucumber', 'Sea urchin', 'Turban shell'],
    activityTypes: ['skin', 'scuba'],
  },
  {
    id: 3,
    name: '범섬',
    region: 'korea',
    country: '한국',
    lat: 33.2190,
    lng: 126.5160,
    depth: '10~45m',
    visibility: '10~25m',
    waterTemp: { min: 14, max: 26 },
    difficulty: 'advanced',
    bestSeason: ['6월', '7월', '8월', '9월', '10월'],
    marineLife: ['대형 연산호', '거북이', '쥐치', '방어', '참돔'],
    description: '서귀포 앞바다의 무인도로, 깊은 수심과 강한 조류가 특징인 상급자용 다이빙 사이트입니다. 대형 연산호와 다양한 대형 어종을 관찰할 수 있습니다.',
    highlights: ['딥다이빙 포인트', '강한 조류 드리프트', '대형 어종 출현'],
    countryEn: 'South Korea',
    nameEn: 'Beomseom',
    descriptionEn: 'An uninhabited island off Seogwipo with deep waters and strong currents, suited for advanced divers. Observe large soft corals and big pelagic fish.',
    highlightsEn: ['Deep diving points', 'Strong current drift diving', 'Large pelagic fish encounters'],
    marineLifeEn: ['Giant soft coral', 'Sea turtle', 'Filefish', 'Yellowtail', 'Red sea bream'],
    activityTypes: ['scuba'],
  },
  {
    id: 4,
    name: '울릉도',
    region: 'korea',
    country: '한국',
    lat: 37.4845,
    lng: 130.9057,
    depth: '5~35m',
    visibility: '15~30m',
    waterTemp: { min: 10, max: 24 },
    difficulty: 'intermediate',
    bestSeason: ['7월', '8월', '9월'],
    marineLife: ['대왕문어', '혹돔', '방어떼', '해조류', '불가사리'],
    description: '동해의 보석 울릉도는 깨끗한 수질과 높은 시야가 자랑입니다. 독특한 화산 지형의 수중 경관과 동해 특유의 해양생물을 만날 수 있습니다.',
    highlights: ['동해 최고 시야', '화산 지형 수중경관', '대왕문어 서식지'],
    countryEn: 'South Korea',
    nameEn: 'Ulleungdo',
    descriptionEn: 'A gem of the East Sea, Ulleungdo boasts pristine water quality and excellent visibility. Explore unique volcanic underwater landscapes and East Sea marine life.',
    highlightsEn: ['Best visibility in East Sea', 'Volcanic underwater scenery', 'Giant octopus habitat'],
    marineLifeEn: ['Giant octopus', 'Knobsnout parrotfish', 'Yellowtail school', 'Seaweed', 'Starfish'],
    activityTypes: ['skin', 'scuba'],
  },
  {
    id: 5,
    name: '거문도',
    region: 'korea',
    country: '한국',
    lat: 34.0280,
    lng: 127.3100,
    depth: '5~30m',
    visibility: '8~20m',
    waterTemp: { min: 14, max: 25 },
    difficulty: 'intermediate',
    bestSeason: ['6월', '7월', '8월', '9월'],
    marineLife: ['연산호', '갯민숭달팽이', '해마', '놀래기', '쥐노래미'],
    description: '전남 여수에 위치한 거문도는 다도해해상국립공원의 일부로, 풍부한 연산호와 다양한 매크로 생물이 특징입니다.',
    highlights: ['다도해 수중경관', '매크로 생물 천국', '연산호 군락'],
    countryEn: 'South Korea',
    nameEn: 'Geomundo',
    descriptionEn: 'Part of Dadohaehaesang National Park in Yeosu, Geomundo features abundant soft corals and diverse macro life.',
    highlightsEn: ['Dadohae underwater scenery', 'Macro life paradise', 'Soft coral colonies'],
    marineLifeEn: ['Soft coral', 'Nudibranch', 'Seahorse', 'Wrasse', 'Rockfish'],
    activityTypes: ['skin', 'scuba'],
  },
  {
    id: 6,
    name: '독도',
    region: 'korea',
    country: '한국',
    lat: 37.2426,
    lng: 131.8597,
    depth: '10~40m',
    visibility: '15~30m',
    waterTemp: { min: 10, max: 23 },
    difficulty: 'advanced',
    bestSeason: ['7월', '8월', '9월'],
    marineLife: ['대형 해조류', '전복', '소라', '혹돔', '방어'],
    description: '대한민국 최동단 독도는 한류와 난류가 만나는 특수한 해역으로, 독특한 수중 생태계를 자랑합니다. 허가가 필요한 특별한 다이빙 사이트입니다.',
    highlights: ['대한민국 최동단 다이빙', '한난류 교차 해역', '특별 허가 필요'],
    countryEn: 'South Korea',
    nameEn: 'Dokdo',
    descriptionEn: 'Korea\'s easternmost island where warm and cold currents meet, creating a unique underwater ecosystem. Special permit required.',
    highlightsEn: ['Korea\'s easternmost diving', 'Warm-cold current crossover', 'Special permit required'],
    marineLifeEn: ['Giant kelp', 'Abalone', 'Turban shell', 'Knobsnout parrotfish', 'Yellowtail'],
    activityTypes: ['scuba'],
  },
  {
    id: 7,
    name: '서귀포 해양공원',
    region: 'korea',
    country: '한국',
    lat: 33.2400,
    lng: 126.5600,
    depth: '3~18m',
    visibility: '8~20m',
    waterTemp: { min: 15, max: 26 },
    difficulty: 'beginner',
    bestSeason: ['5월', '6월', '7월', '8월', '9월', '10월'],
    marineLife: ['열대어', '말미잘', '해삼', '불가사리', '자리돔'],
    description: '서귀포 해양공원은 다양한 수중 생물과 아름다운 산호를 감상할 수 있는 초보자 친화적인 다이빙 사이트입니다.',
    highlights: ['초보자 교육 최적', '얕은 수심', '접근성 우수'],
    countryEn: 'South Korea',
    nameEn: 'Seogwipo Marine Park',
    descriptionEn: 'A beginner-friendly diving site where you can enjoy diverse marine life and beautiful corals in Seogwipo, Jeju.',
    highlightsEn: ['Ideal for beginner training', 'Shallow depth', 'Excellent accessibility'],
    marineLifeEn: ['Tropical fish', 'Sea anemone', 'Sea cucumber', 'Starfish', 'Damselfish'],
    activityTypes: ['skin', 'scuba'],
  },

  // ── 동남아시아 (8곳) ──
  {
    id: 8,
    name: '투바타하 리프',
    region: 'southeast-asia',
    country: '필리핀',
    lat: 8.9167,
    lng: 119.8333,
    depth: '5~40m',
    visibility: '30~45m',
    waterTemp: { min: 27, max: 30 },
    difficulty: 'intermediate',
    bestSeason: ['3월', '4월', '5월', '6월'],
    marineLife: ['만타레이', '상어', '거북이', '바라쿠다', '잭피쉬'],
    description: 'UNESCO 세계자연유산으로 지정된 투바타하 리프는 필리핀 최고의 다이빙 사이트로, 원시 그대로의 산호초와 대형 해양생물을 만날 수 있습니다.',
    highlights: ['UNESCO 세계자연유산', '원시 산호초', '대형 해양생물 집결지'],
    countryEn: 'Philippines',
    nameEn: 'Tubbataha Reef',
    descriptionEn: 'A UNESCO World Natural Heritage site and the Philippines\' premier diving destination, offering pristine coral reefs and large marine life.',
    highlightsEn: ['UNESCO World Natural Heritage', 'Pristine coral reefs', 'Large marine life gathering'],
    marineLifeEn: ['Manta ray', 'Shark', 'Sea turtle', 'Barracuda', 'Jackfish'],
    activityTypes: ['skin', 'scuba'],
  },
  {
    id: 9,
    name: '시밀란 제도',
    region: 'southeast-asia',
    country: '태국',
    lat: 8.6500,
    lng: 97.6500,
    depth: '5~35m',
    visibility: '20~40m',
    waterTemp: { min: 27, max: 30 },
    difficulty: 'beginner',
    bestSeason: ['11월', '12월', '1월', '2월', '3월', '4월'],
    marineLife: ['만타레이', '고래상어', '거북이', '레오파드상어', '리프피쉬'],
    description: '안다만 해에 위치한 시밀란 제도는 세계 10대 다이빙 사이트 중 하나로, 맑은 물과 다양한 대형 해양생물이 특징입니다.',
    highlights: ['세계 10대 다이빙 사이트', '만타레이 포인트', '크리스탈 클리어 시야'],
    countryEn: 'Thailand',
    nameEn: 'Similan Islands',
    descriptionEn: 'One of the world\'s top 10 dive sites in the Andaman Sea, known for crystal-clear water and diverse large marine life.',
    highlightsEn: ['World top 10 dive site', 'Manta ray point', 'Crystal clear visibility'],
    marineLifeEn: ['Manta ray', 'Whale shark', 'Sea turtle', 'Leopard shark', 'Reef fish'],
    activityTypes: ['skin', 'scuba'],
  },
  {
    id: 10,
    name: '코모도 국립공원',
    region: 'southeast-asia',
    country: '인도네시아',
    lat: -8.5500,
    lng: 119.4833,
    depth: '5~40m',
    visibility: '10~30m',
    waterTemp: { min: 24, max: 29 },
    difficulty: 'intermediate',
    bestSeason: ['4월', '5월', '6월', '7월', '8월', '9월', '10월', '11월'],
    marineLife: ['만타레이', '상어', '해마', '갑오징어', '산호'],
    description: '코모도 드래곤으로 유명한 이 국립공원은 수중에서도 놀라운 생물 다양성을 자랑합니다. 강한 조류가 풍부한 영양분을 공급합니다.',
    highlights: ['만타레이 클리닝 스테이션', '강한 조류 다이빙', '놀라운 생물 다양성'],
    countryEn: 'Indonesia',
    nameEn: 'Komodo National Park',
    descriptionEn: 'Famous for Komodo dragons on land, this national park also boasts incredible underwater biodiversity fueled by strong nutrient-rich currents.',
    highlightsEn: ['Manta ray cleaning station', 'Strong current diving', 'Incredible biodiversity'],
    marineLifeEn: ['Manta ray', 'Shark', 'Seahorse', 'Cuttlefish', 'Coral'],
    activityTypes: ['skin', 'scuba'],
  },
  {
    id: 11,
    name: '시파단',
    region: 'southeast-asia',
    country: '말레이시아',
    lat: 4.1147,
    lng: 118.6292,
    depth: '5~40m',
    visibility: '20~40m',
    waterTemp: { min: 26, max: 30 },
    difficulty: 'intermediate',
    bestSeason: ['4월', '5월', '6월', '7월', '8월', '9월', '10월', '11월', '12월'],
    marineLife: ['거북이 떼', '바라쿠다 토네이도', '잭피쉬', '화이트팁상어', '범프헤드'],
    description: '자크 쿠스토가 "보지 않은 예술작품"이라 극찬한 시파단은 거대한 드롭오프와 함께 엄청난 수의 거북이와 물고기 떼를 볼 수 있습니다.',
    highlights: ['바라쿠다 토네이도', '거북이 떼 포인트', '600m 드롭오프 월'],
    countryEn: 'Malaysia',
    nameEn: 'Sipadan',
    descriptionEn: 'Praised by Jacques Cousteau as "an untouched piece of art," Sipadan offers massive drop-offs and incredible numbers of turtles and fish schools.',
    highlightsEn: ['Barracuda tornado', 'Turtle swarm point', '600m drop-off wall'],
    marineLifeEn: ['Turtle swarm', 'Barracuda tornado', 'Jackfish', 'Whitetip shark', 'Bumphead parrotfish'],
    activityTypes: ['skin', 'scuba'],
  },
  {
    id: 12,
    name: '블루코너 (팔라우)',
    region: 'southeast-asia',
    country: '팔라우',
    lat: 7.1167,
    lng: 134.2167,
    depth: '10~35m',
    visibility: '20~50m',
    waterTemp: { min: 27, max: 30 },
    difficulty: 'advanced',
    bestSeason: ['10월', '11월', '12월', '1월', '2월', '3월', '4월'],
    marineLife: ['그레이리프상어', '나폴레옹피쉬', '만타레이', '독수리가오리', '바라쿠다'],
    description: '세계 최고의 다이빙 포인트로 꼽히는 블루코너는 강한 조류와 함께 엄청난 수의 상어와 대형 어종을 볼 수 있는 드리프트 다이빙 사이트입니다.',
    highlights: ['세계 최고 월다이빙', '상어 군무', '후크 다이빙 체험'],
    countryEn: 'Palau',
    nameEn: 'Blue Corner (Palau)',
    descriptionEn: 'Ranked among the world\'s best dive sites, Blue Corner offers strong currents with incredible numbers of sharks and large pelagic fish.',
    highlightsEn: ['World-class wall diving', 'Shark parade', 'Hook diving experience'],
    marineLifeEn: ['Grey reef shark', 'Napoleon wrasse', 'Manta ray', 'Eagle ray', 'Barracuda'],
    activityTypes: ['scuba'],
  },
  {
    id: 13,
    name: '라자 암팟',
    region: 'southeast-asia',
    country: '인도네시아',
    lat: -0.2333,
    lng: 130.5167,
    depth: '5~30m',
    visibility: '10~30m',
    waterTemp: { min: 27, max: 30 },
    difficulty: 'beginner',
    bestSeason: ['10월', '11월', '12월', '1월', '2월', '3월', '4월'],
    marineLife: ['만타레이', '워비공상어', '피그미해마', '누디브랜치', '산호'],
    description: '지구상 해양 생물 다양성이 가장 높은 지역으로, 1,500종 이상의 물고기와 600종 이상의 산호가 서식합니다.',
    highlights: ['지구 최고 생물다양성', '워비공상어 서식지', '원시 산호초'],
    countryEn: 'Indonesia',
    nameEn: 'Raja Ampat',
    descriptionEn: 'The most biodiverse marine region on Earth, home to over 1,500 fish species and 600 coral species.',
    highlightsEn: ['Earth\'s highest biodiversity', 'Wobbegong shark habitat', 'Pristine coral reefs'],
    marineLifeEn: ['Manta ray', 'Wobbegong shark', 'Pygmy seahorse', 'Nudibranch', 'Coral'],
    activityTypes: ['skin', 'scuba'],
  },
  {
    id: 14,
    name: '엘니도',
    region: 'southeast-asia',
    country: '필리핀',
    lat: 11.1784,
    lng: 119.3930,
    depth: '5~30m',
    visibility: '10~25m',
    waterTemp: { min: 26, max: 30 },
    difficulty: 'beginner',
    bestSeason: ['11월', '12월', '1월', '2월', '3월', '4월', '5월'],
    marineLife: ['거북이', '리프피쉬', '넙치', '누디브랜치', '산호'],
    description: '석회암 절벽으로 둘러싸인 엘니도는 아름다운 수중 경관과 함께 다양한 해양생물을 만날 수 있는 초보자 친화적 다이빙 사이트입니다.',
    highlights: ['석회암 절벽 수중경관', '거북이 스노클링', '초보자 추천'],
    countryEn: 'Philippines',
    nameEn: 'El Nido',
    descriptionEn: 'Surrounded by limestone cliffs, El Nido offers beautiful underwater scenery and diverse marine life in a beginner-friendly setting.',
    highlightsEn: ['Limestone cliff underwater scenery', 'Turtle snorkeling', 'Recommended for beginners'],
    marineLifeEn: ['Sea turtle', 'Reef fish', 'Flounder', 'Nudibranch', 'Coral'],
    activityTypes: ['skin', 'scuba'],
  },
  {
    id: 15,
    name: '리슐리외 락',
    region: 'southeast-asia',
    country: '태국',
    lat: 9.3667,
    lng: 98.0167,
    depth: '5~35m',
    visibility: '15~35m',
    waterTemp: { min: 27, max: 30 },
    difficulty: 'intermediate',
    bestSeason: ['11월', '12월', '1월', '2월', '3월', '4월'],
    marineLife: ['고래상어', '만타레이', '해마', '하를레퀸쉬림프', '보라색 산호'],
    description: '태국 최고의 다이빙 사이트로, 보라색 연산호로 뒤덮인 수중 피나클이 장관입니다. 고래상어와의 만남도 기대할 수 있습니다.',
    highlights: ['고래상어 출현 포인트', '보라색 연산호 군락', '매크로 사진 최적'],
    countryEn: 'Thailand',
    nameEn: 'Richelieu Rock',
    descriptionEn: 'Thailand\'s best dive site, featuring a stunning underwater pinnacle covered in purple soft corals. Whale shark encounters are possible.',
    highlightsEn: ['Whale shark sighting point', 'Purple soft coral colony', 'Ideal for macro photography'],
    marineLifeEn: ['Whale shark', 'Manta ray', 'Seahorse', 'Harlequin shrimp', 'Purple coral'],
    activityTypes: ['skin', 'scuba'],
  },

  // ── 오세아니아 (4곳) ──
  {
    id: 16,
    name: '그레이트 배리어 리프',
    region: 'oceania',
    country: '호주',
    lat: -18.2861,
    lng: 147.7000,
    depth: '5~30m',
    visibility: '15~30m',
    waterTemp: { min: 22, max: 29 },
    difficulty: 'beginner',
    bestSeason: ['6월', '7월', '8월', '9월', '10월', '11월'],
    marineLife: ['거북이', '클라운피쉬', '만타레이', '드워프밍크고래', '리프상어'],
    description: '세계 최대의 산호초 지대로, 2,300km에 걸쳐 펼쳐진 거대한 생태계입니다. 드워프밍크고래와의 특별한 만남도 가능합니다.',
    highlights: ['세계 최대 산호초', '드워프밍크고래 스윔', 'UNESCO 세계유산'],
    countryEn: 'Australia',
    nameEn: 'Great Barrier Reef',
    descriptionEn: 'The world\'s largest coral reef system, stretching 2,300km with a massive ecosystem. Dwarf minke whale encounters are possible.',
    highlightsEn: ['World\'s largest coral reef', 'Dwarf minke whale swim', 'UNESCO World Heritage'],
    marineLifeEn: ['Sea turtle', 'Clownfish', 'Manta ray', 'Dwarf minke whale', 'Reef shark'],
    activityTypes: ['skin', 'scuba'],
  },
  {
    id: 17,
    name: '보라보라',
    region: 'oceania',
    country: '프랑스령 폴리네시아',
    lat: -16.5004,
    lng: -151.7415,
    depth: '5~30m',
    visibility: '20~40m',
    waterTemp: { min: 25, max: 29 },
    difficulty: 'beginner',
    bestSeason: ['5월', '6월', '7월', '8월', '9월', '10월', '11월'],
    marineLife: ['블랙팁상어', '레몬상어', '만타레이', '거북이', '독수리가오리'],
    description: '에메랄드빛 라군으로 유명한 보라보라는 상어와 가오리와 함께 하는 편안한 다이빙을 즐길 수 있습니다.',
    highlights: ['상어 피딩 다이빙', '에메랄드 라군', '가오리 포인트'],
    countryEn: 'French Polynesia',
    nameEn: 'Bora Bora',
    descriptionEn: 'Famous for its emerald lagoon, Bora Bora offers relaxed diving with sharks and rays.',
    highlightsEn: ['Shark feeding dive', 'Emerald lagoon', 'Ray point'],
    marineLifeEn: ['Blacktip shark', 'Lemon shark', 'Manta ray', 'Sea turtle', 'Eagle ray'],
    activityTypes: ['skin', 'scuba'],
  },
  {
    id: 18,
    name: '푸어나이츠 제도',
    region: 'oceania',
    country: '뉴질랜드',
    lat: -35.4800,
    lng: 174.7400,
    depth: '10~40m',
    visibility: '15~30m',
    waterTemp: { min: 14, max: 22 },
    difficulty: 'intermediate',
    bestSeason: ['1월', '2월', '3월', '4월', '5월'],
    marineLife: ['쏠배감펭', '킹피쉬', '누디브랜치', '해면', '가오리'],
    description: '쿠스토가 세계 10대 다이빙 사이트로 선정한 푸어나이츠는 아치, 동굴, 터널 등 다양한 수중 지형이 특징입니다.',
    highlights: ['수중 아치와 동굴', '자크 쿠스토 선정', '켈프 숲 다이빙'],
    countryEn: 'New Zealand',
    nameEn: 'Poor Knights Islands',
    descriptionEn: 'Selected by Cousteau as one of the world\'s top 10 dive sites, featuring arches, caves, tunnels and diverse underwater topography.',
    highlightsEn: ['Underwater arches and caves', 'Cousteau\'s top 10 pick', 'Kelp forest diving'],
    marineLifeEn: ['Lionfish', 'Kingfish', 'Nudibranch', 'Sponge', 'Stingray'],
    activityTypes: ['skin', 'scuba'],
  },
  {
    id: 19,
    name: '피지 소모소모 해협',
    region: 'oceania',
    country: '피지',
    lat: -16.8000,
    lng: 179.9833,
    depth: '5~40m',
    visibility: '15~30m',
    waterTemp: { min: 25, max: 29 },
    difficulty: 'intermediate',
    bestSeason: ['4월', '5월', '6월', '7월', '8월', '9월', '10월'],
    marineLife: ['불상어', '화이트팁상어', '연산호', '바라쿠다', '만타레이'],
    description: '세계 연산호 수도로 불리는 피지의 소모소모 해협은 화려한 연산호와 상어 다이빙으로 유명합니다.',
    highlights: ['세계 연산호 수도', '상어 다이빙', '강한 조류 드리프트'],
    countryEn: 'Fiji',
    nameEn: 'Fiji Somosomo Strait',
    descriptionEn: 'Known as the soft coral capital of the world, Somosomo Strait is famous for its vibrant soft corals and shark diving.',
    highlightsEn: ['Soft coral capital of the world', 'Shark diving', 'Strong current drift diving'],
    marineLifeEn: ['Bull shark', 'Whitetip shark', 'Soft coral', 'Barracuda', 'Manta ray'],
    activityTypes: ['skin', 'scuba'],
  },

  // ── 인도양 (4곳) ──
  {
    id: 20,
    name: '몰디브 아리환초',
    region: 'indian-ocean',
    country: '몰디브',
    lat: 3.8500,
    lng: 72.8500,
    depth: '5~35m',
    visibility: '20~40m',
    waterTemp: { min: 27, max: 30 },
    difficulty: 'beginner',
    bestSeason: ['1월', '2월', '3월', '4월', '11월', '12월'],
    marineLife: ['고래상어', '만타레이', '거북이', '모레이일', '리프상어'],
    description: '몰디브 최고의 다이빙 환초로, 고래상어와 만타레이를 가장 높은 확률로 만날 수 있습니다. 크리스탈처럼 맑은 물이 특징입니다.',
    highlights: ['고래상어 보장 포인트', '만타레이 클리닝 스테이션', '오버행 다이빙'],
    countryEn: 'Maldives',
    nameEn: 'Maldives Ari Atoll',
    descriptionEn: 'The Maldives\' premier diving atoll where whale shark and manta ray sightings are almost guaranteed. Crystal-clear water is the hallmark.',
    highlightsEn: ['Guaranteed whale shark point', 'Manta ray cleaning station', 'Overhang diving'],
    marineLifeEn: ['Whale shark', 'Manta ray', 'Sea turtle', 'Moray eel', 'Reef shark'],
    activityTypes: ['skin', 'scuba'],
  },
  {
    id: 21,
    name: '세이셸',
    region: 'indian-ocean',
    country: '세이셸',
    lat: -4.6796,
    lng: 55.4920,
    depth: '5~30m',
    visibility: '15~30m',
    waterTemp: { min: 26, max: 30 },
    difficulty: 'beginner',
    bestSeason: ['3월', '4월', '5월', '10월', '11월'],
    marineLife: ['거북이', '독수리가오리', '고래상어', '리프피쉬', '넙치'],
    description: '인도양의 낙원 세이셸은 화강암 바위가 만들어내는 독특한 수중 지형과 풍부한 해양생물이 특징입니다.',
    highlights: ['화강암 수중 지형', '거북이 보호구역', '투명한 라군'],
    countryEn: 'Seychelles',
    nameEn: 'Seychelles',
    descriptionEn: 'A paradise in the Indian Ocean, Seychelles features unique underwater granite formations and abundant marine life.',
    highlightsEn: ['Granite underwater formations', 'Turtle sanctuary', 'Crystal-clear lagoon'],
    marineLifeEn: ['Sea turtle', 'Eagle ray', 'Whale shark', 'Reef fish', 'Flounder'],
    activityTypes: ['skin', 'scuba'],
  },
  {
    id: 22,
    name: '잔지바르',
    region: 'indian-ocean',
    country: '탄자니아',
    lat: -6.1659,
    lng: 39.1989,
    depth: '5~30m',
    visibility: '15~25m',
    waterTemp: { min: 25, max: 29 },
    difficulty: 'beginner',
    bestSeason: ['10월', '11월', '12월', '1월', '2월', '3월'],
    marineLife: ['돌고래', '거북이', '리프피쉬', '문어', '가오리'],
    description: '아프리카 동해안의 잔지바르는 돌고래와 함께 수영하며 다이빙을 즐길 수 있는 특별한 곳입니다.',
    highlights: ['돌고래 스윔', '스파이스 아일랜드', '산호정원'],
    countryEn: 'Tanzania',
    nameEn: 'Zanzibar',
    descriptionEn: 'Off the East African coast, Zanzibar offers a special diving experience where you can swim with dolphins.',
    highlightsEn: ['Dolphin swim', 'Spice Island', 'Coral garden'],
    marineLifeEn: ['Dolphin', 'Sea turtle', 'Reef fish', 'Octopus', 'Stingray'],
    activityTypes: ['skin', 'scuba'],
  },
  {
    id: 23,
    name: '레위니옹',
    region: 'indian-ocean',
    country: '프랑스령 레위니옹',
    lat: -21.1151,
    lng: 55.5364,
    depth: '10~40m',
    visibility: '10~25m',
    waterTemp: { min: 22, max: 28 },
    difficulty: 'intermediate',
    bestSeason: ['10월', '11월', '12월', '1월', '2월', '3월'],
    marineLife: ['혹등고래', '거북이', '돌고래', '바라쿠다', '리프피쉬'],
    description: '화산섬 레위니옹은 용암이 만들어낸 독특한 수중 지형과 혹등고래 시즌의 특별한 만남이 가능한 곳입니다.',
    highlights: ['혹등고래 시즌(7~10월)', '화산 수중지형', '난파선 다이빙'],
    countryEn: 'Reunion',
    nameEn: 'Reunion',
    descriptionEn: 'Volcanic island Reunion features unique lava-formed underwater terrain and special humpback whale encounters during season.',
    highlightsEn: ['Humpback whale season (Jul-Oct)', 'Volcanic underwater terrain', 'Wreck diving'],
    marineLifeEn: ['Humpback whale', 'Sea turtle', 'Dolphin', 'Barracuda', 'Reef fish'],
    activityTypes: ['skin', 'scuba'],
  },

  // ── 홍해 (4곳) ──
  {
    id: 24,
    name: '라스 모하메드',
    region: 'red-sea',
    country: '이집트',
    lat: 27.7347,
    lng: 34.2534,
    depth: '5~40m',
    visibility: '20~40m',
    waterTemp: { min: 21, max: 28 },
    difficulty: 'intermediate',
    bestSeason: ['3월', '4월', '5월', '6월', '9월', '10월', '11월'],
    marineLife: ['잭피쉬 토네이도', '바라쿠다', '나폴레옹피쉬', '상어', '거북이'],
    description: '시나이 반도 끝에 위치한 라스 모하메드는 홍해 최고의 다이빙 사이트로, 웅장한 드롭오프와 거대한 물고기 떼가 장관입니다.',
    highlights: ['샤크 리프 & 요란다 리프', '잭피쉬 월', '맑은 시야'],
    countryEn: 'Egypt',
    nameEn: 'Ras Mohammed',
    descriptionEn: 'Located at the tip of Sinai Peninsula, Ras Mohammed is the Red Sea\'s premier dive site with magnificent drop-offs and massive fish schools.',
    highlightsEn: ['Shark Reef & Yolanda Reef', 'Jackfish wall', 'Excellent visibility'],
    marineLifeEn: ['Jackfish tornado', 'Barracuda', 'Napoleon wrasse', 'Shark', 'Sea turtle'],
    activityTypes: ['skin', 'scuba'],
  },
  {
    id: 25,
    name: 'SS 시슬곰 난파선',
    region: 'red-sea',
    country: '이집트',
    lat: 27.8619,
    lng: 34.3061,
    depth: '15~30m',
    visibility: '15~30m',
    waterTemp: { min: 21, max: 28 },
    difficulty: 'intermediate',
    bestSeason: ['3월', '4월', '5월', '9월', '10월', '11월'],
    marineLife: ['라이온피쉬', '글래스피쉬', '모레이일', '바라쿠다', '리프피쉬'],
    description: '1941년 독일 폭격으로 침몰한 영국 화물선으로, 세계에서 가장 유명한 난파선 다이빙 포인트 중 하나입니다.',
    highlights: ['세계 최고 난파선 다이빙', '역사적 화물선', '풍부한 해양생물'],
    countryEn: 'Egypt',
    nameEn: 'SS Thistlegorm Wreck',
    descriptionEn: 'A British cargo ship sunk by German bombs in 1941, one of the world\'s most famous wreck diving sites.',
    highlightsEn: ['World-class wreck diving', 'Historic cargo ship', 'Rich marine life'],
    marineLifeEn: ['Lionfish', 'Glassfish', 'Moray eel', 'Barracuda', 'Reef fish'],
    activityTypes: ['skin', 'scuba'],
  },
  {
    id: 26,
    name: '다합',
    region: 'red-sea',
    country: '이집트',
    lat: 28.4913,
    lng: 34.5131,
    depth: '5~100m+',
    visibility: '20~40m',
    waterTemp: { min: 21, max: 28 },
    difficulty: 'beginner',
    bestSeason: ['3월', '4월', '5월', '9월', '10월', '11월'],
    marineLife: ['블루홀 원양어류', '거북이', '리프피쉬', '산호', '라이온피쉬'],
    description: '세계적으로 유명한 블루홀이 있는 다합은 프리다이버와 스쿠버다이버 모두에게 사랑받는 곳입니다. 해안 다이빙이 가능합니다.',
    highlights: ['블루홀 (깊이 100m+)', '해안 진입 다이빙', '프리다이빙 성지'],
    countryEn: 'Egypt',
    nameEn: 'Dahab',
    descriptionEn: 'Home to the world-famous Blue Hole, Dahab is loved by both freedivers and scuba divers. Shore diving is possible.',
    highlightsEn: ['Blue Hole (100m+ depth)', 'Shore entry diving', 'Freediving mecca'],
    marineLifeEn: ['Blue Hole pelagics', 'Sea turtle', 'Reef fish', 'Coral', 'Lionfish'],
    activityTypes: ['skin', 'scuba'],
  },
  {
    id: 27,
    name: '브라더스 제도',
    region: 'red-sea',
    country: '이집트',
    lat: 26.3200,
    lng: 34.8500,
    depth: '10~60m+',
    visibility: '20~40m',
    waterTemp: { min: 22, max: 28 },
    difficulty: 'advanced',
    bestSeason: ['5월', '6월', '7월', '9월', '10월', '11월'],
    marineLife: ['귀상어 떼', '화이트팁상어', '만타레이', '나폴레옹피쉬', '참치'],
    description: '홍해 한가운데 위치한 외딴 섬으로, 리브어보드로만 접근 가능합니다. 귀상어 떼와 대형 상어를 만날 수 있는 홍해 최고의 상어 포인트입니다.',
    highlights: ['귀상어 떼', '리브어보드 전용', '홍해 최고 상어 포인트'],
    countryEn: 'Egypt',
    nameEn: 'Brothers Islands',
    descriptionEn: 'Remote islands in the middle of the Red Sea, accessible only by liveaboard. The best shark point in the Red Sea for hammerhead schools.',
    highlightsEn: ['Hammerhead shark school', 'Liveaboard only', 'Red Sea\'s best shark point'],
    marineLifeEn: ['Hammerhead school', 'Whitetip shark', 'Manta ray', 'Napoleon wrasse', 'Tuna'],
    activityTypes: ['scuba'],
  },

  // ── 카리브해 (4곳) ──
  {
    id: 28,
    name: '코수멜',
    region: 'caribbean',
    country: '멕시코',
    lat: 20.4318,
    lng: -86.9203,
    depth: '5~35m',
    visibility: '20~40m',
    waterTemp: { min: 25, max: 29 },
    difficulty: 'beginner',
    bestSeason: ['3월', '4월', '5월', '6월', '11월', '12월'],
    marineLife: ['거북이', '간호사상어', '독수리가오리', '스플렌디드토드피쉬', '산호'],
    description: '멕시코 카리브해의 코수멜은 세계적으로 유명한 드리프트 다이빙 사이트로, 편안한 조류를 타며 아름다운 산호 월을 감상할 수 있습니다.',
    highlights: ['편안한 드리프트 다이빙', '산호 월 다이빙', '스플렌디드토드피쉬'],
    countryEn: 'Mexico',
    nameEn: 'Cozumel',
    descriptionEn: 'World-renowned drift diving destination in the Mexican Caribbean, where you glide along beautiful coral walls with gentle currents.',
    highlightsEn: ['Comfortable drift diving', 'Coral wall diving', 'Splendid toadfish'],
    marineLifeEn: ['Sea turtle', 'Nurse shark', 'Eagle ray', 'Splendid toadfish', 'Coral'],
    activityTypes: ['skin', 'scuba'],
  },
  {
    id: 29,
    name: '벨리즈 블루홀',
    region: 'caribbean',
    country: '벨리즈',
    lat: 17.3155,
    lng: -87.5347,
    depth: '40~130m',
    visibility: '30~60m',
    waterTemp: { min: 26, max: 29 },
    difficulty: 'advanced',
    bestSeason: ['4월', '5월', '6월'],
    marineLife: ['리프상어', '불상어', '거대 종유석', '바라쿠다', '엔젤피쉬'],
    description: '직경 300m, 깊이 130m의 거대한 싱크홀은 세계에서 가장 유명한 다이빙 사이트 중 하나입니다. 수중 종유석이 장관입니다.',
    highlights: ['세계 최대 블루홀', '수중 종유석', '항공 촬영 명소'],
    countryEn: 'Belize',
    nameEn: 'Belize Blue Hole',
    descriptionEn: 'A giant sinkhole 300m in diameter and 130m deep, one of the world\'s most famous dive sites. Underwater stalactites are spectacular.',
    highlightsEn: ['World\'s largest blue hole', 'Underwater stalactites', 'Iconic aerial view'],
    marineLifeEn: ['Reef shark', 'Bull shark', 'Giant stalactites', 'Barracuda', 'Angelfish'],
    activityTypes: ['scuba'],
  },
  {
    id: 30,
    name: '보네르',
    region: 'caribbean',
    country: '네덜란드령 안틸레스',
    lat: 12.1443,
    lng: -68.2655,
    depth: '5~40m',
    visibility: '20~40m',
    waterTemp: { min: 26, max: 29 },
    difficulty: 'beginner',
    bestSeason: ['1월', '2월', '3월', '4월', '5월', '6월', '7월', '8월', '9월', '10월', '11월', '12월'],
    marineLife: ['해마', '거북이', '리프피쉬', '문어', '해면'],
    description: '다이버의 천국 보네르는 해안에서 직접 입수할 수 있는 80개 이상의 다이빙 사이트를 보유하고 있습니다. 연중 다이빙이 가능합니다.',
    highlights: ['해안 진입 다이빙', '연중 다이빙 가능', '80+ 다이빙 사이트'],
    countryEn: 'Netherlands Antilles',
    nameEn: 'Bonaire',
    descriptionEn: 'Diver\'s paradise Bonaire has over 80 shore-entry dive sites. Year-round diving is possible.',
    highlightsEn: ['Shore entry diving', 'Year-round diving', '80+ dive sites'],
    marineLifeEn: ['Seahorse', 'Sea turtle', 'Reef fish', 'Octopus', 'Sponge'],
    activityTypes: ['skin', 'scuba'],
  },
  {
    id: 31,
    name: '케이맨 제도',
    region: 'caribbean',
    country: '케이맨 제도',
    lat: 19.3133,
    lng: -81.2546,
    depth: '5~40m',
    visibility: '25~40m',
    waterTemp: { min: 26, max: 29 },
    difficulty: 'beginner',
    bestSeason: ['3월', '4월', '5월', '6월', '11월', '12월'],
    marineLife: ['가오리', '거북이', '리프상어', '타폰', '엔젤피쉬'],
    description: '스팅레이 시티로 유명한 케이맨 제도는 가오리와 직접 교감할 수 있는 특별한 경험을 제공합니다.',
    highlights: ['스팅레이 시티', '키트윙키 난파선', '월 다이빙'],
    countryEn: 'Cayman Islands',
    nameEn: 'Cayman Islands',
    descriptionEn: 'Famous for Stingray City, the Cayman Islands offer a special experience interacting directly with stingrays.',
    highlightsEn: ['Stingray City', 'Kittiwake wreck', 'Wall diving'],
    marineLifeEn: ['Stingray', 'Sea turtle', 'Reef shark', 'Tarpon', 'Angelfish'],
    activityTypes: ['skin', 'scuba'],
  },

  // ── 유럽 (4곳) ──
  {
    id: 32,
    name: '아조레스 제도',
    region: 'europe',
    country: '포르투갈',
    lat: 37.7833,
    lng: -25.5000,
    depth: '10~40m',
    visibility: '15~40m',
    waterTemp: { min: 16, max: 24 },
    difficulty: 'intermediate',
    bestSeason: ['6월', '7월', '8월', '9월', '10월'],
    marineLife: ['블루상어', '모불라가오리', '돌고래', '향유고래', '참치'],
    description: '대서양 한가운데 위치한 아조레스는 대형 원양어류와의 만남이 보장되는 유럽 최고의 다이빙 목적지입니다.',
    highlights: ['블루상어 다이빙', '향유고래 스윔', '대서양 원양어류'],
    countryEn: 'Portugal',
    nameEn: 'Azores',
    descriptionEn: 'Located in the middle of the Atlantic, the Azores guarantee encounters with large pelagic species — Europe\'s premier diving destination.',
    highlightsEn: ['Blue shark diving', 'Sperm whale swim', 'Atlantic pelagics'],
    marineLifeEn: ['Blue shark', 'Mobula ray', 'Dolphin', 'Sperm whale', 'Tuna'],
    activityTypes: ['skin', 'scuba'],
  },
  {
    id: 33,
    name: '몰타 블루홀',
    region: 'europe',
    country: '몰타',
    lat: 36.0566,
    lng: 14.2130,
    depth: '5~35m',
    visibility: '20~40m',
    waterTemp: { min: 15, max: 27 },
    difficulty: 'beginner',
    bestSeason: ['5월', '6월', '7월', '8월', '9월', '10월'],
    marineLife: ['문어', '바라쿠다', '앰버잭', '뱀장어', '해면'],
    description: '고조 섬의 블루홀은 자연이 만들어낸 수중 아치와 동굴로 유명하며, 유럽에서 가장 아름다운 다이빙 사이트 중 하나입니다.',
    highlights: ['천연 수중 아치', '아주르 윈도우', '해안 진입 다이빙'],
    countryEn: 'Malta',
    nameEn: 'Malta Blue Hole',
    descriptionEn: 'The Blue Hole on Gozo Island is famous for its natural underwater arches and caves — one of Europe\'s most beautiful dive sites.',
    highlightsEn: ['Natural underwater arch', 'Azure Window', 'Shore entry diving'],
    marineLifeEn: ['Octopus', 'Barracuda', 'Amberjack', 'Moray eel', 'Sponge'],
    activityTypes: ['skin', 'scuba'],
  },
  {
    id: 34,
    name: '크로아티아 비스섬',
    region: 'europe',
    country: '크로아티아',
    lat: 43.0600,
    lng: 16.1900,
    depth: '5~50m',
    visibility: '20~40m',
    waterTemp: { min: 13, max: 25 },
    difficulty: 'intermediate',
    bestSeason: ['5월', '6월', '7월', '8월', '9월', '10월'],
    marineLife: ['문어', '바라쿠다', '참돔', '로브스터', '해면'],
    description: '아드리아해의 숨겨진 보석 비스섬은 2차 세계대전 난파선과 수중 동굴 다이빙이 가능한 유럽의 인기 다이빙 사이트입니다.',
    highlights: ['2차대전 난파선', '블루 동굴', '아드리아해 투명한 물'],
    countryEn: 'Croatia',
    nameEn: 'Vis Island, Croatia',
    descriptionEn: 'A hidden gem of the Adriatic, Vis Island offers WWII wreck diving and underwater cave exploration.',
    highlightsEn: ['WWII wrecks', 'Blue Cave', 'Crystal-clear Adriatic water'],
    marineLifeEn: ['Octopus', 'Barracuda', 'Red sea bream', 'Lobster', 'Sponge'],
    activityTypes: ['skin', 'scuba'],
  },
  {
    id: 35,
    name: '노르웨이 로포텐',
    region: 'europe',
    country: '노르웨이',
    lat: 68.2000,
    lng: 14.4000,
    depth: '5~30m',
    visibility: '10~25m',
    waterTemp: { min: 4, max: 14 },
    difficulty: 'advanced',
    bestSeason: ['1월', '2월', '3월', '9월', '10월'],
    marineLife: ['범고래', '대구', '킹크랩', '해조류', '해삼'],
    description: '북극권에 위치한 로포텐은 범고래와 함께 다이빙할 수 있는 세계에서 몇 안 되는 곳 중 하나입니다. 오로라 시즌에는 환상적인 야간 다이빙도 가능합니다.',
    highlights: ['범고래 다이빙', '오로라 나이트다이빙', '북극권 콜드워터'],
    countryEn: 'Norway',
    nameEn: 'Lofoten, Norway',
    descriptionEn: 'Located above the Arctic Circle, Lofoten is one of the few places where you can dive with orcas. Spectacular night diving under the Northern Lights is possible.',
    highlightsEn: ['Orca diving', 'Aurora night diving', 'Arctic cold water diving'],
    marineLifeEn: ['Orca', 'Cod', 'King crab', 'Seaweed', 'Sea cucumber'],
    activityTypes: ['skin', 'scuba'],
  },

  // ── 동아시아 (2곳) ──
  {
    id: 36,
    name: '오키나와 게라마 제도',
    region: 'east-asia',
    country: '일본',
    lat: 26.1900,
    lng: 127.3000,
    depth: '5~35m',
    visibility: '20~40m',
    waterTemp: { min: 21, max: 29 },
    difficulty: 'beginner',
    bestSeason: ['4월', '5월', '6월', '7월', '8월', '9월', '10월'],
    marineLife: ['만타레이', '거북이', '클라운피쉬', '산호', '해마'],
    description: '오키나와의 게라마 제도는 "케라마 블루"로 불리는 투명한 바다와 만타레이 포인트로 유명합니다.',
    highlights: ['케라마 블루', '만타레이 포인트', '거북이 서식지'],
    countryEn: 'Japan',
    nameEn: 'Okinawa Kerama Islands',
    descriptionEn: 'The Kerama Islands are famous for "Kerama Blue" crystal-clear water and manta ray points.',
    highlightsEn: ['Kerama Blue', 'Manta ray point', 'Turtle habitat'],
    marineLifeEn: ['Manta ray', 'Sea turtle', 'Clownfish', 'Coral', 'Seahorse'],
    activityTypes: ['skin', 'scuba'],
  },
  {
    id: 37,
    name: '란위 (대만)',
    region: 'east-asia',
    country: '대만',
    lat: 22.0500,
    lng: 121.5500,
    depth: '5~30m',
    visibility: '20~40m',
    waterTemp: { min: 23, max: 29 },
    difficulty: 'beginner',
    bestSeason: ['4월', '5월', '6월', '7월', '8월', '9월', '10월'],
    marineLife: ['플라잉피쉬', '클라운피쉬', '거북이', '산호', '리프피쉬'],
    description: '대만 동남쪽의 란위(난유)는 원주민 타오족의 독특한 문화와 함께 아름다운 수중 세계를 경험할 수 있는 곳입니다.',
    highlights: ['플라잉피쉬 시즌', '원주민 타오 문화', '화산섬 다이빙'],
    countryEn: 'Taiwan',
    nameEn: 'Lanyu (Taiwan)',
    descriptionEn: 'Southeast of Taiwan, Lanyu (Orchid Island) offers the unique Tao indigenous culture alongside a beautiful underwater world.',
    highlightsEn: ['Flying fish season', 'Tao indigenous culture', 'Volcanic island diving'],
    marineLifeEn: ['Flying fish', 'Clownfish', 'Sea turtle', 'Coral', 'Reef fish'],
    activityTypes: ['skin', 'scuba'],
  },

  // ── 태평양 (1곳) ──
  {
    id: 38,
    name: '갈라파고스',
    region: 'pacific',
    country: '에콰도르',
    lat: -0.9538,
    lng: -90.9656,
    depth: '10~40m',
    visibility: '10~25m',
    waterTemp: { min: 16, max: 26 },
    difficulty: 'advanced',
    bestSeason: ['6월', '7월', '8월', '9월', '10월', '11월'],
    marineLife: ['귀상어 수백마리', '고래상어', '바다이구아나', '물개', '만타레이'],
    description: '다윈의 진화론이 탄생한 갈라파고스는 수백 마리의 귀상어 떼와 바다이구아나 등 이곳에서만 볼 수 있는 생물들로 가득합니다.',
    highlights: ['귀상어 수백마리 군무', '바다이구아나', '다윈의 섬'],
    countryEn: 'Ecuador',
    nameEn: 'Galapagos',
    descriptionEn: 'The birthplace of Darwin\'s theory of evolution, the Galapagos is filled with unique species like hundreds of hammerhead sharks and marine iguanas.',
    highlightsEn: ['Hundreds of hammerhead sharks', 'Marine iguana', 'Darwin\'s islands'],
    marineLifeEn: ['Hundreds of hammerheads', 'Whale shark', 'Marine iguana', 'Sea lion', 'Manta ray'],
    activityTypes: ['scuba'],
  },

  // ── 추가: 동남아시아 (8곳) ──
  {
    id: 39,
    name: '모알보알',
    region: 'southeast-asia',
    country: '필리핀',
    lat: 9.9464,
    lng: 123.3686,
    depth: '3~42m',
    visibility: '12~20m',
    waterTemp: { min: 26, max: 30 },
    difficulty: 'beginner',
    bestSeason: ['1월', '2월', '3월', '4월', '5월', '11월', '12월'],
    marineLife: ['정어리 수백만마리', '거북이', '환도상어', '고래상어', '바라쿠다'],
    description: '세부 모알보알은 수백만 마리의 정어리 떼가 연중 거대한 군무를 펼치는 세계적인 사딘런 포인트입니다. 해안에서 바로 입수하여 장관을 감상할 수 있습니다.',
    highlights: ['사딘런 (연중 상시)', '해안 진입 다이빙', '거북이 대량 서식'],
    countryEn: 'Philippines',
    nameEn: 'Moalboal',
    descriptionEn: 'Cebu\'s Moalboal is a world-class sardine run point where millions of sardines perform a spectacular bait ball year-round. Shore entry diving.',
    highlightsEn: ['Sardine run (year-round)', 'Shore entry diving', 'Large turtle population'],
    marineLifeEn: ['Millions of sardines', 'Sea turtle', 'Thresher shark', 'Whale shark', 'Barracuda'],
    activityTypes: ['skin', 'scuba'],
  },
  {
    id: 40,
    name: '말라파스쿠아',
    region: 'southeast-asia',
    country: '필리핀',
    lat: 11.3267,
    lng: 124.1156,
    depth: '12~30m',
    visibility: '10~25m',
    waterTemp: { min: 25, max: 30 },
    difficulty: 'intermediate',
    bestSeason: ['11월', '12월', '1월', '2월', '3월', '4월', '5월'],
    marineLife: ['환도상어', '만타레이', '화이트팁상어', '해마', '누디브랜치'],
    description: '세계에서 환도상어(Thresher Shark)를 가장 높은 확률로 만날 수 있는 곳입니다. 이른 아침 모나드 숄에서 클리닝 스테이션을 방문하는 환도상어를 관찰합니다.',
    highlights: ['환도상어 클리닝 스테이션', '이른 아침 다이빙', '매크로 생물 풍부'],
    countryEn: 'Philippines',
    nameEn: 'Malapascua',
    descriptionEn: 'The best place in the world to see thresher sharks. Observe them visiting cleaning stations at Monad Shoal in early morning dives.',
    highlightsEn: ['Thresher shark cleaning station', 'Early morning dives', 'Rich macro life'],
    marineLifeEn: ['Thresher shark', 'Manta ray', 'Whitetip shark', 'Seahorse', 'Nudibranch'],
    activityTypes: ['skin', 'scuba'],
  },
  {
    id: 41,
    name: '아닐라오',
    region: 'southeast-asia',
    country: '필리핀',
    lat: 13.7630,
    lng: 120.9290,
    depth: '5~40m',
    visibility: '5~25m',
    waterTemp: { min: 24, max: 29 },
    difficulty: 'beginner',
    bestSeason: ['11월', '12월', '1월', '2월', '3월', '4월', '5월'],
    marineLife: ['누디브랜치 600종', '프로그피쉬', '피그미해마', '플람보얀트커틀피쉬', '블루링옥토퍼스'],
    description: '세계 누디브랜치(갯민숭달팽이) 수도로 불리며, 전 세계 800종 중 600종 이상이 서식합니다. 매크로 수중촬영가들의 성지입니다.',
    highlights: ['누디브랜치 수도', '매크로 촬영 성지', '마닐라 근접 접근성'],
    countryEn: 'Philippines',
    nameEn: 'Anilao',
    descriptionEn: 'Known as the nudibranch capital of the world with 600+ of 800 known species. A mecca for macro underwater photographers.',
    highlightsEn: ['Nudibranch capital', 'Macro photography mecca', 'Close to Manila'],
    marineLifeEn: ['600+ nudibranch species', 'Frogfish', 'Pygmy seahorse', 'Flamboyant cuttlefish', 'Blue-ringed octopus'],
    activityTypes: ['skin', 'scuba'],
  },
  {
    id: 42,
    name: '세일 락',
    region: 'southeast-asia',
    country: '태국',
    lat: 9.6833,
    lng: 100.0167,
    depth: '5~40m',
    visibility: '10~30m',
    waterTemp: { min: 27, max: 30 },
    difficulty: 'intermediate',
    bestSeason: ['3월', '4월', '5월', '6월', '7월', '8월', '9월'],
    marineLife: ['고래상어', '바라쿠다', '잭피쉬', '배트피쉬', '그루퍼'],
    description: '태국 만(Gulf of Thailand) 최고의 다이빙 사이트로, 수면 위 8m까지 솟은 바위와 내부 침니(굴뚝) 지형이 독특합니다. 고래상어 출현 확률이 높습니다.',
    highlights: ['침니(굴뚝) 관통 다이빙', '고래상어 출현', '거대 바라쿠다 떼'],
    countryEn: 'Thailand',
    nameEn: 'Sail Rock',
    descriptionEn: 'The best dive site in the Gulf of Thailand, with a rock rising 8m above the surface and a unique chimney formation. High chance of whale shark sighting.',
    highlightsEn: ['Chimney swim-through', 'Whale shark sightings', 'Giant barracuda school'],
    marineLifeEn: ['Whale shark', 'Barracuda', 'Jackfish', 'Batfish', 'Grouper'],
    activityTypes: ['skin', 'scuba'],
  },
  {
    id: 43,
    name: '누사 페니다 만타 포인트',
    region: 'southeast-asia',
    country: '인도네시아',
    lat: -8.7347,
    lng: 115.4442,
    depth: '5~18m',
    visibility: '10~30m',
    waterTemp: { min: 18, max: 28 },
    difficulty: 'intermediate',
    bestSeason: ['4월', '5월', '6월', '7월', '8월', '9월', '10월'],
    marineLife: ['만타레이', '몰라몰라(개복치)', '블루링옥토퍼스', '거북이', '리프상어'],
    description: '발리 누사 페니다의 만타 포인트는 연중 만타레이를 높은 확률로 만날 수 있는 클리닝 스테이션입니다. 7~10월에는 개복치(몰라몰라)도 출현합니다.',
    highlights: ['만타레이 클리닝 스테이션', '몰라몰라 시즌(7~10월)', '발리 근접'],
    countryEn: 'Indonesia',
    nameEn: 'Nusa Penida Manta Point',
    descriptionEn: 'A year-round manta ray cleaning station off Bali\'s Nusa Penida. Mola mola (ocean sunfish) appear from Jul to Oct.',
    highlightsEn: ['Manta ray cleaning station', 'Mola mola season (Jul-Oct)', 'Close to Bali'],
    marineLifeEn: ['Manta ray', 'Mola mola (ocean sunfish)', 'Blue-ringed octopus', 'Sea turtle', 'Reef shark'],
    activityTypes: ['skin', 'scuba'],
  },
  {
    id: 44,
    name: '뚤람벤 USAT 리버티',
    region: 'southeast-asia',
    country: '인도네시아',
    lat: -8.2764,
    lng: 115.5928,
    depth: '3~30m',
    visibility: '10~25m',
    waterTemp: { min: 26, max: 30 },
    difficulty: 'beginner',
    bestSeason: ['4월', '5월', '6월', '7월', '8월', '9월', '10월', '11월'],
    marineLife: ['범프헤드패롯피쉬', '잭피쉬', '바라쿠다', '피그미해마', '누디브랜치'],
    description: '2차 대전 중 일본군 어뢰에 피격된 미군 수송선 USAT 리버티가 해안에서 40m 거리에 침몰해 있습니다. 세계에서 가장 접근성이 좋은 난파선 다이빙 사이트입니다.',
    highlights: ['해안 진입 난파선', '초보자 가능 렉다이빙', '새벽 범프헤드 떼'],
    countryEn: 'Indonesia',
    nameEn: 'Tulamben USAT Liberty',
    descriptionEn: 'A WWII US transport ship torpedoed by Japan, resting just 40m from shore. The world\'s most accessible wreck dive site.',
    highlightsEn: ['Shore entry wreck', 'Beginner-friendly wreck diving', 'Dawn bumphead school'],
    marineLifeEn: ['Bumphead parrotfish', 'Jackfish', 'Barracuda', 'Pygmy seahorse', 'Nudibranch'],
    activityTypes: ['skin', 'scuba'],
  },
  {
    id: 45,
    name: '렘베 해협',
    region: 'southeast-asia',
    country: '인도네시아',
    lat: 1.4833,
    lng: 125.2500,
    depth: '5~25m',
    visibility: '5~20m',
    waterTemp: { min: 25, max: 29 },
    difficulty: 'intermediate',
    bestSeason: ['3월', '4월', '5월', '6월', '7월', '8월', '9월', '10월'],
    marineLife: ['헤어리프로그피쉬', '미믹옥토퍼스', '플람보얀트커틀피쉬', '원더퍼스', '코코넛옥토퍼스'],
    description: '세계 머크다이빙의 수도로 불리는 렘베 해협은 모래와 진흙 바닥에서 기상천외한 생물들을 찾아내는 매크로 다이빙의 성지입니다.',
    highlights: ['세계 머크다이빙 수도', '기상천외한 매크로 생물', '수중촬영 천국'],
    countryEn: 'Indonesia',
    nameEn: 'Lembeh Strait',
    descriptionEn: 'Known as the muck diving capital of the world. Discover bizarre creatures on sandy and muddy bottoms — a macro diving mecca.',
    highlightsEn: ['Muck diving capital of the world', 'Bizarre macro creatures', 'Underwater photography paradise'],
    marineLifeEn: ['Hairy frogfish', 'Mimic octopus', 'Flamboyant cuttlefish', 'Wonderpus', 'Coconut octopus'],
    activityTypes: ['skin', 'scuba'],
  },
  {
    id: 46,
    name: '센데라와시 만',
    region: 'southeast-asia',
    country: '인도네시아',
    lat: -2.1500,
    lng: 134.9500,
    depth: '5~35m',
    visibility: '10~30m',
    waterTemp: { min: 27, max: 30 },
    difficulty: 'intermediate',
    bestSeason: ['6월', '7월', '8월', '9월', '10월', '11월'],
    marineLife: ['고래상어', '산호', '리프피쉬', '거북이', '만타레이'],
    description: '파푸아 센데라와시 만에서는 어부의 뜰채(바간) 아래에서 먹이를 먹는 고래상어와 함께 다이빙할 수 있는 세계 유일의 경험을 제공합니다.',
    highlights: ['고래상어와 근접 다이빙', '바간(뜰채) 포인트', '파푸아 원시 산호초'],
    countryEn: 'Indonesia',
    nameEn: 'Cenderawasih Bay',
    descriptionEn: 'In Papua\'s Cenderawasih Bay, dive alongside whale sharks feeding under fishermen\'s bagan nets — a unique experience found nowhere else.',
    highlightsEn: ['Close-up whale shark diving', 'Bagan (lift-net) point', 'Papua pristine coral reefs'],
    marineLifeEn: ['Whale shark', 'Coral', 'Reef fish', 'Sea turtle', 'Manta ray'],
    activityTypes: ['skin', 'scuba'],
  },

  // ── 추가: 태평양 (7곳) ──
  {
    id: 47,
    name: '추크 라군 (트럭 라군)',
    region: 'pacific',
    country: '미크로네시아',
    lat: 7.4167,
    lng: 151.7833,
    depth: '12~65m',
    visibility: '12~25m',
    waterTemp: { min: 27, max: 29 },
    difficulty: 'intermediate',
    bestSeason: ['12월', '1월', '2월', '3월', '4월'],
    marineLife: ['산호가 뒤덮은 난파선', '라이온피쉬', '상어', '가오리', '바라쿠다'],
    description: '2차 대전 일본 해군 함대가 침몰한 세계 최고의 난파선 다이빙 성지입니다. 60척 이상의 침몰 함선과 항공기가 산호로 뒤덮여 인공 산호초를 이루고 있습니다.',
    highlights: ['세계 최고 난파선 다이빙', '60척 이상 침몰 함선', '역사적 2차대전 유적'],
    countryEn: 'Micronesia',
    nameEn: 'Chuuk Lagoon (Truk Lagoon)',
    descriptionEn: 'The world\'s premier wreck diving site with 60+ WWII Japanese naval vessels and aircraft, now covered in coral forming artificial reefs.',
    highlightsEn: ['World\'s best wreck diving', '60+ sunken warships', 'Historic WWII relics'],
    marineLifeEn: ['Coral-covered wrecks', 'Lionfish', 'Shark', 'Stingray', 'Barracuda'],
    activityTypes: ['skin', 'scuba'],
  },
  {
    id: 48,
    name: '통가 바바우',
    region: 'pacific',
    country: '통가',
    lat: -18.6500,
    lng: -173.9833,
    depth: '5~30m',
    visibility: '20~40m',
    waterTemp: { min: 21, max: 28 },
    difficulty: 'intermediate',
    bestSeason: ['7월', '8월', '9월', '10월'],
    marineLife: ['혹등고래', '리프상어', '거북이', '바라쿠다', '산호'],
    description: '매년 7~10월 혹등고래가 번식을 위해 찾아오는 통가 바바우는 고래와 함께 수영할 수 있는 세계 몇 안 되는 합법적인 장소 중 하나입니다.',
    highlights: ['혹등고래 스윔', '합법적 고래 수영', '투명한 남태평양 바다'],
    countryEn: 'Tonga',
    nameEn: 'Tonga Vava\'u',
    descriptionEn: 'Humpback whales visit Tonga\'s Vava\'u every Jul-Oct for breeding. One of the few legal places to swim with whales.',
    highlightsEn: ['Humpback whale swim', 'Legal whale swimming', 'Crystal-clear South Pacific'],
    marineLifeEn: ['Humpback whale', 'Reef shark', 'Sea turtle', 'Barracuda', 'Coral'],
    activityTypes: ['skin', 'scuba'],
  },
  {
    id: 49,
    name: '랑기로아',
    region: 'pacific',
    country: '프랑스령 폴리네시아',
    lat: -15.1333,
    lng: -147.6333,
    depth: '15~40m',
    visibility: '15~40m',
    waterTemp: { min: 26, max: 29 },
    difficulty: 'advanced',
    bestSeason: ['1월', '2월', '3월', '6월', '7월', '8월', '9월', '10월', '11월'],
    marineLife: ['그레이리프상어', '귀상어', '독수리가오리', '돌고래', '바라쿠다'],
    description: '세계에서 두 번째로 큰 환초인 랑기로아의 티푸타 패스는 강한 조류와 함께 수백 마리의 상어를 만나는 드리프트 다이빙으로 유명합니다.',
    highlights: ['티푸타 패스 드리프트', '상어 수백마리 군무', '쿠스토가 극찬한 다이빙'],
    countryEn: 'French Polynesia',
    nameEn: 'Rangiroa',
    descriptionEn: 'The world\'s second-largest atoll. Tiputa Pass is famous for drift diving through strong currents alongside hundreds of sharks.',
    highlightsEn: ['Tiputa Pass drift', 'Hundreds of sharks', 'Cousteau\'s acclaimed dive'],
    marineLifeEn: ['Grey reef shark', 'Hammerhead', 'Eagle ray', 'Dolphin', 'Barracuda'],
    activityTypes: ['scuba'],
  },
  {
    id: 50,
    name: '파카라바',
    region: 'pacific',
    country: '프랑스령 폴리네시아',
    lat: -16.0500,
    lng: -145.6167,
    depth: '10~30m',
    visibility: '10~30m',
    waterTemp: { min: 26, max: 28 },
    difficulty: 'intermediate',
    bestSeason: ['5월', '6월', '7월', '8월', '9월', '10월'],
    marineLife: ['그레이리프상어 벽', '레몬상어', '귀상어', '오셔닉화이트팁', '그루퍼'],
    description: 'UNESCO 생물권보전지역으로 지정된 파카라바의 남쪽 패스에서는 수백 마리의 상어가 벽을 이루는 "샤크 월"을 볼 수 있습니다.',
    highlights: ['샤크 월 (상어 벽)', 'UNESCO 생물권보전지역', '미끼 없는 자연 상어 다이빙'],
    countryEn: 'French Polynesia',
    nameEn: 'Fakarava',
    descriptionEn: 'A UNESCO Biosphere Reserve where hundreds of sharks form a "shark wall" at the south pass.',
    highlightsEn: ['Shark wall', 'UNESCO Biosphere Reserve', 'Natural no-bait shark diving'],
    marineLifeEn: ['Grey reef shark wall', 'Lemon shark', 'Hammerhead', 'Oceanic whitetip', 'Grouper'],
    activityTypes: ['skin', 'scuba'],
  },
  {
    id: 51,
    name: '코코스 섬',
    region: 'pacific',
    country: '코스타리카',
    lat: 5.5500,
    lng: -87.0500,
    depth: '15~40m',
    visibility: '10~30m',
    waterTemp: { min: 24, max: 28 },
    difficulty: 'advanced',
    bestSeason: ['6월', '7월', '8월', '9월', '10월', '11월', '12월'],
    marineLife: ['귀상어 대군', '화이트팁상어', '고래상어', '만타레이', '돌고래'],
    description: '코스타리카에서 550km 떨어진 외딴 섬으로, 리브어보드로만 접근 가능합니다. 수백 마리의 귀상어 떼를 만나는 세계 최고의 귀상어 다이빙 포인트입니다.',
    highlights: ['세계 최고 귀상어 포인트', '리브어보드 전용', '원양 대형 어류 집결지'],
    countryEn: 'Costa Rica',
    nameEn: 'Cocos Island',
    descriptionEn: 'A remote island 550km from Costa Rica, accessible only by liveaboard. The world\'s best hammerhead diving with hundreds in a single dive.',
    highlightsEn: ['World\'s best hammerhead point', 'Liveaboard only', 'Pelagic gathering'],
    marineLifeEn: ['Hammerhead army', 'Whitetip shark', 'Whale shark', 'Manta ray', 'Dolphin'],
    activityTypes: ['scuba'],
  },
  {
    id: 52,
    name: '소코로 제도',
    region: 'pacific',
    country: '멕시코',
    lat: 18.7900,
    lng: -110.9600,
    depth: '15~35m',
    visibility: '15~40m',
    waterTemp: { min: 21, max: 28 },
    difficulty: 'advanced',
    bestSeason: ['11월', '12월', '1월', '2월', '3월', '4월', '5월'],
    marineLife: ['자이언트 만타레이', '고래상어', '혹등고래', '돌고래', '귀상어'],
    description: '멕시코 태평양의 외딴 화산섬군으로, 리브어보드로만 접근 가능합니다. 날개 폭 5m 이상의 자이언트 오셔닉 만타레이와의 만남이 특별합니다.',
    highlights: ['자이언트 만타레이', '혹등고래 시즌(1~4월)', '리브어보드 전용'],
    countryEn: 'Mexico',
    nameEn: 'Socorro Islands',
    descriptionEn: 'Remote volcanic islands in the Mexican Pacific, accessible only by liveaboard. Giant oceanic manta rays with 5m+ wingspans are the highlight.',
    highlightsEn: ['Giant oceanic manta ray', 'Humpback whale season (Jan-Apr)', 'Liveaboard only'],
    marineLifeEn: ['Giant manta ray', 'Whale shark', 'Humpback whale', 'Dolphin', 'Hammerhead'],
    activityTypes: ['scuba'],
  },
  {
    id: 53,
    name: '말펠로 섬',
    region: 'pacific',
    country: '콜롬비아',
    lat: 4.0000,
    lng: -81.6117,
    depth: '15~40m',
    visibility: '10~30m',
    waterTemp: { min: 15, max: 28 },
    difficulty: 'advanced',
    bestSeason: ['1월', '2월', '3월', '4월', '5월'],
    marineLife: ['귀상어 200~300마리', '실키상어', '고래상어', '독수리가오리', '참치'],
    description: '콜롬비아에서 500km 떨어진 외딴 화산섬으로, 한 다이브에서 200~300마리의 귀상어를 동시에 만날 수 있는 "상어 다이빙의 수도"입니다.',
    highlights: ['상어 다이빙의 수도', '귀상어 200~300마리', 'UNESCO 세계자연유산'],
    countryEn: 'Colombia',
    nameEn: 'Malpelo Island',
    descriptionEn: 'A remote volcanic island 500km from Colombia, the "shark diving capital" where you can encounter 200-300 hammerheads in a single dive.',
    highlightsEn: ['Shark diving capital', '200-300 hammerheads', 'UNESCO World Natural Heritage'],
    marineLifeEn: ['200-300 hammerheads', 'Silky shark', 'Whale shark', 'Eagle ray', 'Tuna'],
    activityTypes: ['scuba'],
  },

  // ── 추가: 카리브해 (4곳) ──
  {
    id: 54,
    name: '세노테 (유카탄)',
    region: 'caribbean',
    country: '멕시코',
    lat: 20.2467,
    lng: -87.4292,
    depth: '5~15m',
    visibility: '50~100m+',
    waterTemp: { min: 24, max: 25 },
    difficulty: 'beginner',
    bestSeason: ['1월', '2월', '3월', '4월', '5월', '6월', '7월', '8월', '9월', '10월', '11월', '12월'],
    marineLife: ['수중 종유석', '할로클라인', '민물 생물', '블라인드 케이브피쉬', '화석 산호'],
    description: '유카탄 반도의 세노테는 수만 년에 걸쳐 형성된 석회암 수중 동굴 시스템입니다. 100m 이상의 놀라운 시야와 신비로운 빛의 커튼이 압도적입니다.',
    highlights: ['100m+ 초투명 시야', '빛의 커튼 현상', '수중 종유석·석순'],
    countryEn: 'Mexico',
    nameEn: 'Cenotes (Yucatan)',
    descriptionEn: 'Yucatan\'s cenotes are limestone underwater cave systems formed over millennia. Over 100m visibility and mystical light curtains are breathtaking.',
    highlightsEn: ['100m+ ultra-clear visibility', 'Light curtain effect', 'Underwater stalactites & stalagmites'],
    marineLifeEn: ['Underwater stalactites', 'Halocline', 'Freshwater species', 'Blind cave fish', 'Fossil coral'],
    activityTypes: ['skin', 'scuba'],
  },
  {
    id: 55,
    name: '타이거 비치',
    region: 'caribbean',
    country: '바하마',
    lat: 26.8600,
    lng: -79.0500,
    depth: '5~12m',
    visibility: '20~40m',
    waterTemp: { min: 24, max: 29 },
    difficulty: 'advanced',
    bestSeason: ['10월', '11월', '12월', '1월'],
    marineLife: ['타이거상어', '레몬상어', '그레이트해머헤드', '캐리비안리프상어', '간호사상어'],
    description: '바하마의 얕은 모래 평원에서 다수의 타이거 상어를 근접 관찰할 수 있는 세계 최고의 상어 다이빙 사이트입니다.',
    highlights: ['타이거 상어 근접 관찰', '얕은 수심 롱 다이빙', '상어 수중촬영 최적'],
    countryEn: 'Bahamas',
    nameEn: 'Tiger Beach',
    descriptionEn: 'A world-class shark diving site on the shallow sand flats of the Bahamas where multiple tiger sharks can be observed up close.',
    highlightsEn: ['Close-up tiger shark observation', 'Shallow water long dives', 'Ideal for shark photography'],
    marineLifeEn: ['Tiger shark', 'Lemon shark', 'Great hammerhead', 'Caribbean reef shark', 'Nurse shark'],
    activityTypes: ['skin', 'scuba'],
  },
  {
    id: 56,
    name: '카보 풀모',
    region: 'caribbean',
    country: '멕시코',
    lat: 23.4433,
    lng: -109.4236,
    depth: '5~20m',
    visibility: '6~30m',
    waterTemp: { min: 18, max: 29 },
    difficulty: 'beginner',
    bestSeason: ['6월', '7월', '8월', '9월', '10월', '11월'],
    marineLife: ['잭피쉬 토네이도', '불상어', '모불라가오리', '바다사자', '고래상어'],
    description: '멕시코 바하 칼리포르니아 국립공원으로, 20년간 보호 노력의 결과 해양생물이 460% 증가한 보존 성공 사례입니다.',
    highlights: ['잭피쉬 토네이도', '해양 보전 성공 사례', '바다사자 다이빙'],
    countryEn: 'Mexico',
    nameEn: 'Cabo Pulmo',
    descriptionEn: 'A Baja California national park where 20 years of conservation efforts resulted in a 460% increase in marine life — a conservation success story.',
    highlightsEn: ['Jackfish tornado', 'Marine conservation success', 'Sea lion diving'],
    marineLifeEn: ['Jackfish tornado', 'Bull shark', 'Mobula ray', 'Sea lion', 'Whale shark'],
    activityTypes: ['skin', 'scuba'],
  },
  {
    id: 57,
    name: '로아탄',
    region: 'caribbean',
    country: '온두라스',
    lat: 16.3226,
    lng: -86.5354,
    depth: '5~40m',
    visibility: '20~30m',
    waterTemp: { min: 25, max: 29 },
    difficulty: 'beginner',
    bestSeason: ['3월', '4월', '5월', '6월', '7월', '8월', '9월', '10월'],
    marineLife: ['리프상어', '거북이', '독수리가오리', '산호', '해마'],
    description: '세계 두 번째로 큰 메소아메리칸 배리어 리프에 위치한 로아탄은 접근성이 좋고 가성비가 뛰어난 카리브해 다이빙 메카입니다.',
    highlights: ['메소아메리칸 배리어 리프', '가성비 최고 다이빙', '다양한 월 다이빙'],
    countryEn: 'Honduras',
    nameEn: 'Roatan',
    descriptionEn: 'Located on the Mesoamerican Barrier Reef, the second largest in the world, Roatan is an accessible and great-value Caribbean diving mecca.',
    highlightsEn: ['Mesoamerican Barrier Reef', 'Best value diving', 'Diverse wall diving'],
    marineLifeEn: ['Reef shark', 'Sea turtle', 'Eagle ray', 'Coral', 'Seahorse'],
    activityTypes: ['skin', 'scuba'],
  },

  // ── 추가: 홍해 (1곳) ──
  {
    id: 58,
    name: '엘핀스톤 리프',
    region: 'red-sea',
    country: '이집트',
    lat: 25.2933,
    lng: 34.8600,
    depth: '10~60m+',
    visibility: '15~35m',
    waterTemp: { min: 22, max: 28 },
    difficulty: 'advanced',
    bestSeason: ['3월', '4월', '5월', '6월', '9월', '10월', '11월'],
    marineLife: ['오셔닉화이트팁상어', '귀상어', '바라쿠다', '나폴레옹피쉬', '부채산호'],
    description: '마르사 알람 앞바다 12km에 위치한 장보형 리프로, 홍해에서 오셔닉 화이트팁 상어를 가장 높은 확률로 만날 수 있는 포인트입니다.',
    highlights: ['오셔닉 화이트팁 상어', '드라마틱 드롭오프', '홍해 상어 다이빙 명소'],
    countryEn: 'Egypt',
    nameEn: 'Elphinstone Reef',
    descriptionEn: 'A torpedo-shaped reef 12km off Marsa Alam, the highest probability point for oceanic whitetip sharks in the Red Sea.',
    highlightsEn: ['Oceanic whitetip shark', 'Dramatic drop-off', 'Red Sea shark diving hotspot'],
    marineLifeEn: ['Oceanic whitetip shark', 'Hammerhead', 'Barracuda', 'Napoleon wrasse', 'Fan coral'],
    activityTypes: ['scuba'],
  },

  // ── 추가: 유럽 (1곳) ──
  {
    id: 59,
    name: '실프라 (아이슬란드)',
    region: 'europe',
    country: '아이슬란드',
    lat: 64.2558,
    lng: -21.1164,
    depth: '5~18m',
    visibility: '80~100m+',
    waterTemp: { min: 2, max: 4 },
    difficulty: 'intermediate',
    bestSeason: ['1월', '2월', '3월', '4월', '5월', '6월', '7월', '8월', '9월', '10월', '11월', '12월'],
    marineLife: ['민물 조류', '이끼', '지질 구조물', '빙하수 지형', '용암 지형'],
    description: '유라시아판과 북미판 사이의 틈에서 다이빙하는 세계 유일의 사이트입니다. 빙하수가 용암을 통해 수십 년간 여과되어 100m 이상의 초투명 시야를 자랑합니다.',
    highlights: ['두 대륙판 사이 다이빙', '100m+ 초투명 시야', '드라이수트 필수'],
    countryEn: 'Iceland',
    nameEn: 'Silfra (Iceland)',
    descriptionEn: 'The world\'s only site to dive between tectonic plates. Glacial water filtered through lava for decades offers 100m+ visibility.',
    highlightsEn: ['Diving between two tectonic plates', '100m+ ultra-clear visibility', 'Drysuit required'],
    marineLifeEn: ['Freshwater algae', 'Moss', 'Geological formations', 'Glacial water terrain', 'Lava formations'],
    activityTypes: ['skin', 'scuba'],
  },

  // ── 추가: 동아시아 (1곳) ──
  {
    id: 60,
    name: '요나구니 해저유적',
    region: 'east-asia',
    country: '일본',
    lat: 24.4350,
    lng: 122.9880,
    depth: '5~25m',
    visibility: '30~50m',
    waterTemp: { min: 22, max: 29 },
    difficulty: 'advanced',
    bestSeason: ['11월', '12월', '1월', '2월', '3월', '4월', '5월'],
    marineLife: ['귀상어', '만타레이', '바라쿠다', '거북이', '참치'],
    description: '일본 최서단 요나구니 섬 해저에 잠긴 거대한 계단형 석조 구조물은 자연 형성인지 고대 유적인지 여전히 논쟁 중인 미스터리한 다이빙 사이트입니다.',
    highlights: ['미스터리 해저 유적', '귀상어 시즌(11~5월)', '일본 최서단 다이빙'],
    countryEn: 'Japan',
    nameEn: 'Yonaguni Underwater Ruins',
    descriptionEn: 'Massive stepped stone structures submerged off Japan\'s westernmost island — still debated whether natural or ancient man-made ruins.',
    highlightsEn: ['Mysterious underwater ruins', 'Hammerhead season (Nov-May)', 'Japan\'s westernmost diving'],
    marineLifeEn: ['Hammerhead', 'Manta ray', 'Barracuda', 'Sea turtle', 'Tuna'],
    activityTypes: ['skin', 'scuba'],
  },

  // ── 추가: 인도양 (2곳) ──
  {
    id: 61,
    name: '하니파루 베이',
    region: 'indian-ocean',
    country: '몰디브',
    lat: 5.2472,
    lng: 73.2131,
    depth: '3~20m',
    visibility: '10~25m',
    waterTemp: { min: 27, max: 30 },
    difficulty: 'beginner',
    bestSeason: ['6월', '7월', '8월', '9월', '10월', '11월'],
    marineLife: ['만타레이 100마리+', '고래상어', '플랑크톤', '리프피쉬', '거북이'],
    description: 'UNESCO 생물권보전지역으로 100마리 이상의 만타레이가 동시에 플랑크톤을 먹는 세계 최대의 만타 피딩 사이트입니다.',
    highlights: ['세계 최대 만타 피딩', '100마리+ 만타 동시 출현', 'UNESCO 보전지역'],
    countryEn: 'Maldives',
    nameEn: 'Hanifaru Bay',
    descriptionEn: 'A UNESCO Biosphere Reserve where 100+ manta rays simultaneously feed on plankton — the world\'s largest manta feeding site.',
    highlightsEn: ['World\'s largest manta feeding', '100+ mantas at once', 'UNESCO conservation area'],
    marineLifeEn: ['100+ manta rays', 'Whale shark', 'Plankton', 'Reef fish', 'Sea turtle'],
    activityTypes: ['skin', 'scuba'],
  },
  {
    id: 62,
    name: '소드와나 베이',
    region: 'indian-ocean',
    country: '남아프리카공화국',
    lat: -27.5350,
    lng: 32.6800,
    depth: '5~30m',
    visibility: '8~30m',
    waterTemp: { min: 19, max: 27 },
    difficulty: 'intermediate',
    bestSeason: ['4월', '5월', '6월', '7월', '8월', '9월'],
    marineLife: ['래기드투스상어', '거북이', '고래상어', '돌고래', '열대어'],
    description: '남아프리카 동해안의 소드와나 베이는 아프리카 최남단 산호초 시스템으로, 열대와 아열대 해양생물이 공존하는 독특한 생태계를 자랑합니다.',
    highlights: ['아프리카 최남단 산호초', '래기드투스 상어 서식지', '열대-아열대 교차 생태계'],
    countryEn: 'South Africa',
    nameEn: 'Sodwana Bay',
    descriptionEn: 'Africa\'s southernmost coral reef system on South Africa\'s east coast, with a unique ecosystem where tropical and subtropical marine life coexist.',
    highlightsEn: ['Africa\'s southernmost coral reef', 'Ragged-tooth shark habitat', 'Tropical-subtropical crossover'],
    marineLifeEn: ['Ragged-tooth shark', 'Sea turtle', 'Whale shark', 'Dolphin', 'Tropical fish'],
    activityTypes: ['skin', 'scuba'],
  },

  // ── 추가: 오세아니아 (1곳) ──
  {
    id: 63,
    name: '닝갈루 리프',
    region: 'oceania',
    country: '호주',
    lat: -22.6950,
    lng: 113.6550,
    depth: '5~25m',
    visibility: '10~30m',
    waterTemp: { min: 20, max: 28 },
    difficulty: 'beginner',
    bestSeason: ['3월', '4월', '5월', '6월', '7월'],
    marineLife: ['고래상어', '만타레이', '혹등고래', '거북이', '돌고래'],
    description: '호주 서해안의 닝갈루 리프는 세계에서 가장 큰 거초(fringing reef)로, 매년 3~7월 고래상어가 대거 방문합니다. 해안에서 바로 산호초에 진입할 수 있습니다.',
    highlights: ['고래상어 시즌(3~7월)', '해안 진입 산호초', 'UNESCO 세계유산'],
    countryEn: 'Australia',
    nameEn: 'Ningaloo Reef',
    descriptionEn: 'The world\'s largest fringing reef on Australia\'s west coast, visited by whale sharks every Mar-Jul. Shore entry to the coral reef.',
    highlightsEn: ['Whale shark season (Mar-Jul)', 'Shore entry reef', 'UNESCO World Heritage'],
    marineLifeEn: ['Whale shark', 'Manta ray', 'Humpback whale', 'Sea turtle', 'Dolphin'],
    activityTypes: ['skin', 'scuba'],
  },

  // ── 한국 추가 (14곳) ──

  // 제주도 7곳
  {
    id: 64,
    name: '섶섬',
    nameEn: 'Seopseom',
    region: 'korea',
    country: '한국',
    countryEn: 'South Korea',
    lat: 33.2370,
    lng: 126.5710,
    depth: '5~30m',
    visibility: '10~25m',
    waterTemp: { min: 14, max: 26 },
    difficulty: 'intermediate',
    bestSeason: ['6월', '7월', '8월', '9월', '10월'],
    marineLife: ['연산호', '해마', '쏠배감펭', '거북이', '갑오징어'],
    marineLifeEn: ['Soft coral', 'Seahorse', 'Lionfish', 'Sea turtle', 'Cuttlefish'],
    description: '서귀포 앞바다에 위치한 무인도로, 문섬과 함께 제주 대표 다이빙 포인트입니다. 풍부한 연산호 군락과 다양한 열대어가 서식합니다.',
    descriptionEn: 'An uninhabited island off Seogwipo alongside Munseom, one of Jeju\'s premier dive points. Rich soft coral colonies and diverse tropical fish.',
    highlights: ['문섬과 쌍벽을 이루는 포인트', '풍부한 연산호 군락', '다양한 열대어 서식'],
    highlightsEn: ['Twin dive point with Munseom', 'Rich soft coral colonies', 'Diverse tropical fish habitat'],
    activityTypes: ['skin', 'scuba'],
  },
  {
    id: 65,
    name: '차귀도',
    nameEn: 'Chagwido',
    region: 'korea',
    country: '한국',
    countryEn: 'South Korea',
    lat: 33.3130,
    lng: 126.1510,
    depth: '5~30m',
    visibility: '8~20m',
    waterTemp: { min: 14, max: 25 },
    difficulty: 'intermediate',
    bestSeason: ['6월', '7월', '8월', '9월'],
    marineLife: ['자리돔', '돌돔', '연산호', '해삼', '소라'],
    marineLifeEn: ['Damselfish', 'Rock bream', 'Soft coral', 'Sea cucumber', 'Turban shell'],
    description: '제주 서쪽 최대 무인도로, 수중에는 다양한 암반 지형과 해조류 숲이 펼쳐져 있습니다. 조류가 있어 중급 이상 다이버에게 적합합니다.',
    descriptionEn: 'The largest uninhabited island off western Jeju, with diverse rock formations and seaweed forests underwater. Currents suit intermediate+ divers.',
    highlights: ['제주 서쪽 최대 무인도', '다양한 암반 지형', '해조류 숲 경관'],
    highlightsEn: ['Largest uninhabited island in western Jeju', 'Diverse rock formations', 'Seaweed forest scenery'],
    activityTypes: ['skin', 'scuba'],
  },
  {
    id: 66,
    name: '비양도',
    nameEn: 'Biyangdo',
    region: 'korea',
    country: '한국',
    countryEn: 'South Korea',
    lat: 33.4050,
    lng: 126.2310,
    depth: '5~20m',
    visibility: '8~20m',
    waterTemp: { min: 14, max: 25 },
    difficulty: 'beginner',
    bestSeason: ['6월', '7월', '8월', '9월'],
    marineLife: ['자리돔', '해삼', '불가사리', '소라', '해조류'],
    marineLifeEn: ['Damselfish', 'Sea cucumber', 'Starfish', 'Turban shell', 'Seaweed'],
    description: '한림 앞바다의 작은 화산섬으로, 완만한 수중 지형과 얕은 수심이 특징입니다. 초보 다이버 교육에 많이 이용됩니다.',
    descriptionEn: 'A small volcanic island off Hallim with gentle terrain and shallow depths. Widely used for beginner diver training.',
    highlights: ['초보자 교육 포인트', '완만한 수중 지형', '화산섬 경관'],
    highlightsEn: ['Beginner training point', 'Gentle underwater terrain', 'Volcanic island scenery'],
    activityTypes: ['skin', 'scuba'],
  },
  {
    id: 67,
    name: '송악산',
    nameEn: 'Songaksan',
    region: 'korea',
    country: '한국',
    countryEn: 'South Korea',
    lat: 33.2120,
    lng: 126.2920,
    depth: '5~22m',
    visibility: '8~20m',
    waterTemp: { min: 14, max: 25 },
    difficulty: 'beginner',
    bestSeason: ['6월', '7월', '8월', '9월', '10월'],
    marineLife: ['연산호', '자리돔', '돌돔', '성게', '해삼'],
    marineLifeEn: ['Soft coral', 'Damselfish', 'Rock bream', 'Sea urchin', 'Sea cucumber'],
    description: '제주 남서부 송악산 해안의 다이빙 포인트로, 화산 지형이 만든 독특한 수중 경관을 감상할 수 있습니다.',
    descriptionEn: 'A diving point along the Songaksan coast in southwest Jeju, featuring unique underwater scenery shaped by volcanic terrain.',
    highlights: ['화산 지형 수중 경관', '다양한 해양 생물', '비교적 잔잔한 해역'],
    highlightsEn: ['Volcanic terrain underwater scenery', 'Diverse marine life', 'Relatively calm waters'],
    activityTypes: ['skin', 'scuba'],
  },
  {
    id: 68,
    name: '대포주상절리',
    nameEn: 'Daepo Columnar Joints',
    region: 'korea',
    country: '한국',
    countryEn: 'South Korea',
    lat: 33.2380,
    lng: 126.4250,
    depth: '5~18m',
    visibility: '8~15m',
    waterTemp: { min: 15, max: 26 },
    difficulty: 'beginner',
    bestSeason: ['5월', '6월', '7월', '8월', '9월', '10월'],
    marineLife: ['자리돔', '놀래기', '해삼', '말미잘', '불가사리'],
    marineLifeEn: ['Damselfish', 'Wrasse', 'Sea cucumber', 'Sea anemone', 'Starfish'],
    description: '제주 중문 앞바다로, 육상의 주상절리가 수중에서도 이어지는 독특한 지질 구조를 가진 다이빙 포인트입니다.',
    descriptionEn: 'Off Jungmun, Jeju, where the famous columnar joint formations extend underwater, creating a unique geological diving experience.',
    highlights: ['수중 주상절리 지형', '독특한 지질 구조', '접근성 우수'],
    highlightsEn: ['Underwater columnar joints', 'Unique geological formations', 'Excellent accessibility'],
    activityTypes: ['skin', 'scuba'],
  },
  {
    id: 69,
    name: '형제섬',
    nameEn: 'Hyeongjedo',
    region: 'korea',
    country: '한국',
    countryEn: 'South Korea',
    lat: 33.1950,
    lng: 126.2560,
    depth: '8~35m',
    visibility: '10~25m',
    waterTemp: { min: 14, max: 25 },
    difficulty: 'intermediate',
    bestSeason: ['6월', '7월', '8월', '9월', '10월'],
    marineLife: ['연산호', '방어', '참돔', '쏠배감펭', '가오리'],
    marineLifeEn: ['Soft coral', 'Yellowtail', 'Red sea bream', 'Lionfish', 'Stingray'],
    description: '제주 남서부에 위치한 두 개의 무인 바위섬으로, 깊은 수심과 조류가 있어 중급 이상 다이버에게 적합합니다. 대형 어종 출현 확률이 높습니다.',
    descriptionEn: 'Two uninhabited rocky islets off southwest Jeju with deep water and currents suited for intermediate+ divers. High chance of big fish encounters.',
    highlights: ['대형 어종 출현', '수중 절벽 다이빙', '조류 드리프트 가능'],
    highlightsEn: ['Big fish encounters', 'Cliff diving', 'Current drift diving'],
    activityTypes: ['skin', 'scuba'],
  },
  {
    id: 70,
    name: '한림 협재',
    nameEn: 'Hallim Hyeopjae',
    region: 'korea',
    country: '한국',
    countryEn: 'South Korea',
    lat: 33.3940,
    lng: 126.2390,
    depth: '3~15m',
    visibility: '5~15m',
    waterTemp: { min: 14, max: 25 },
    difficulty: 'beginner',
    bestSeason: ['6월', '7월', '8월', '9월'],
    marineLife: ['자리돔', '해삼', '소라', '성게', '해조류'],
    marineLifeEn: ['Damselfish', 'Sea cucumber', 'Turban shell', 'Sea urchin', 'Seaweed'],
    description: '제주 북서부 협재 해수욕장 일대의 얕은 수심 포인트로, 스노클링과 체험 다이빙에 최적화된 장소입니다.',
    descriptionEn: 'A shallow point near Hyeopjae Beach in northwest Jeju, ideal for snorkeling and introductory dives.',
    highlights: ['스노클링 최적 포인트', '얕은 수심', '아름다운 백사장'],
    highlightsEn: ['Best snorkeling point', 'Shallow depth', 'Beautiful white sand beach'],
    activityTypes: ['skin', 'scuba'],
  },

  // 울릉도 5곳
  {
    id: 71,
    name: '죽도',
    nameEn: 'Jukdo',
    region: 'korea',
    country: '한국',
    countryEn: 'South Korea',
    lat: 37.4990,
    lng: 130.9320,
    depth: '9~35m',
    visibility: '15~30m',
    waterTemp: { min: 10, max: 24 },
    difficulty: 'intermediate',
    bestSeason: ['7월', '8월', '9월'],
    marineLife: ['대왕문어', '방어떼', '혹돔', '해조류', '성게'],
    marineLifeEn: ['Giant octopus', 'Yellowtail school', 'Knobsnout parrotfish', 'Seaweed', 'Sea urchin'],
    description: '울릉도 동쪽의 부속 섬으로, 맑은 동해 바다와 풍부한 해조류 숲이 특징입니다. 대왕문어와 방어 떼를 관찰할 수 있습니다.',
    descriptionEn: 'A satellite island east of Ulleungdo with crystal-clear East Sea waters and rich seaweed forests. Observe giant octopus and yellowtail schools.',
    highlights: ['울릉도 대표 다이빙 포인트', '풍부한 해조류 숲', '대왕문어 서식'],
    highlightsEn: ['Ulleungdo\'s premier dive point', 'Rich seaweed forests', 'Giant octopus habitat'],
    activityTypes: ['skin', 'scuba'],
  },
  {
    id: 72,
    name: '통구미',
    nameEn: 'Tonggumi',
    region: 'korea',
    country: '한국',
    countryEn: 'South Korea',
    lat: 37.4770,
    lng: 130.8570,
    depth: '3~18m',
    visibility: '10~25m',
    waterTemp: { min: 10, max: 24 },
    difficulty: 'beginner',
    bestSeason: ['7월', '8월', '9월'],
    marineLife: ['거북손', '해삼', '성게', '해조류', '불가사리'],
    marineLifeEn: ['Goose barnacle', 'Sea cucumber', 'Sea urchin', 'Seaweed', 'Starfish'],
    description: '울릉도 남서쪽 해안의 거북바위로 유명한 포인트입니다. 얕은 수심과 다양한 해조류로 초보 다이버에게 적합합니다.',
    descriptionEn: 'Famous for its turtle-shaped rock on Ulleungdo\'s southwest coast. Shallow depth and diverse seaweed make it suitable for beginners.',
    highlights: ['거북바위 수중 경관', '풍부한 해조류', '초보자 친화적'],
    highlightsEn: ['Turtle rock underwater scenery', 'Rich seaweed', 'Beginner-friendly'],
    activityTypes: ['skin', 'scuba'],
  },
  {
    id: 73,
    name: '현포',
    nameEn: 'Hyeonpo',
    region: 'korea',
    country: '한국',
    countryEn: 'South Korea',
    lat: 37.5100,
    lng: 130.8510,
    depth: '3~20m',
    visibility: '10~25m',
    waterTemp: { min: 10, max: 24 },
    difficulty: 'beginner',
    bestSeason: ['7월', '8월', '9월'],
    marineLife: ['해조류', '불가사리', '해삼', '소라', '성게'],
    marineLifeEn: ['Seaweed', 'Starfish', 'Sea cucumber', 'Turban shell', 'Sea urchin'],
    description: '울릉도 북서쪽의 조용한 포구로, 화산 지형이 만들어낸 독특한 수중 경관과 맑은 물이 특징입니다.',
    descriptionEn: 'A quiet harbor on Ulleungdo\'s northwest side, featuring unique volcanic underwater terrain and clear water.',
    highlights: ['조용한 포구 다이빙', '화산 지형', '맑은 시야'],
    highlightsEn: ['Quiet harbor diving', 'Volcanic terrain', 'Clear visibility'],
    activityTypes: ['skin', 'scuba'],
  },
  {
    id: 74,
    name: '사동',
    nameEn: 'Sadong',
    region: 'korea',
    country: '한국',
    countryEn: 'South Korea',
    lat: 37.4710,
    lng: 130.9150,
    depth: '5~30m',
    visibility: '15~30m',
    waterTemp: { min: 10, max: 24 },
    difficulty: 'intermediate',
    bestSeason: ['7월', '8월', '9월'],
    marineLife: ['방어', '혹돔', '대왕문어', '해조류', '감태'],
    marineLifeEn: ['Yellowtail', 'Knobsnout parrotfish', 'Giant octopus', 'Seaweed', 'Kelp'],
    description: '울릉도 남동쪽의 사동항 인근 포인트로, 깊은 수심과 풍부한 어종이 특징입니다. 동해의 투명한 시야를 자랑합니다.',
    descriptionEn: 'Near Sadong Port on Ulleungdo\'s southeast, with deep water and rich fish species. Known for the East Sea\'s outstanding visibility.',
    highlights: ['깊은 수심 다이빙', '풍부한 어종', '동해 투명 시야'],
    highlightsEn: ['Deep water diving', 'Rich fish species', 'East Sea clear visibility'],
    activityTypes: ['skin', 'scuba'],
  },
  {
    id: 75,
    name: '학포',
    nameEn: 'Hakpo',
    region: 'korea',
    country: '한국',
    countryEn: 'South Korea',
    lat: 37.5050,
    lng: 130.8650,
    depth: '5~25m',
    visibility: '10~25m',
    waterTemp: { min: 10, max: 24 },
    difficulty: 'beginner',
    bestSeason: ['7월', '8월', '9월'],
    marineLife: ['해조류', '방어', '문어', '불가사리', '해삼'],
    marineLifeEn: ['Seaweed', 'Yellowtail', 'Octopus', 'Starfish', 'Sea cucumber'],
    description: '울릉도 북쪽의 아름다운 해안선을 따라 펼쳐진 포인트로, 기암절벽과 풍부한 해조류 숲이 매력적입니다.',
    descriptionEn: 'Along Ulleungdo\'s beautiful northern coastline, featuring picturesque cliffs and lush seaweed forests.',
    highlights: ['기암절벽 수중 경관', '해조류 숲', '아름다운 해안선'],
    highlightsEn: ['Cliff underwater scenery', 'Seaweed forests', 'Beautiful coastline'],
    activityTypes: ['skin', 'scuba'],
  },

  // 기타 한국 2곳
  {
    id: 76,
    name: '속초 장사항',
    nameEn: 'Sokcho Jangsahang',
    region: 'korea',
    country: '한국',
    countryEn: 'South Korea',
    lat: 38.2070,
    lng: 128.6020,
    depth: '5~20m',
    visibility: '5~15m',
    waterTemp: { min: 8, max: 23 },
    difficulty: 'beginner',
    bestSeason: ['7월', '8월', '9월'],
    marineLife: ['해조류', '문어', '성게', '불가사리', '쥐노래미'],
    marineLifeEn: ['Seaweed', 'Octopus', 'Sea urchin', 'Starfish', 'Rockfish'],
    description: '강원도 속초의 장사항은 동해안에서 접근성이 가장 좋은 다이빙 포인트 중 하나로, 다양한 동해 생물을 관찰할 수 있습니다.',
    descriptionEn: 'Jangsahang in Sokcho, Gangwon-do, is one of the most accessible dive points on the East Sea coast, with diverse East Sea marine life.',
    highlights: ['동해안 접근성 최고', '다양한 동해 생물', '해안 진입 다이빙'],
    highlightsEn: ['Best East Sea accessibility', 'Diverse East Sea marine life', 'Shore entry diving'],
    activityTypes: ['skin', 'scuba'],
  },
  {
    id: 77,
    name: '추자도',
    nameEn: 'Chujado',
    region: 'korea',
    country: '한국',
    countryEn: 'South Korea',
    lat: 33.9500,
    lng: 126.3000,
    depth: '5~30m',
    visibility: '8~20m',
    waterTemp: { min: 14, max: 25 },
    difficulty: 'intermediate',
    bestSeason: ['6월', '7월', '8월', '9월'],
    marineLife: ['방어', '참돔', '돌돔', '연산호', '해조류'],
    marineLifeEn: ['Yellowtail', 'Red sea bream', 'Rock bream', 'Soft coral', 'Seaweed'],
    description: '제주와 전남 사이에 위치한 추자도는 한류와 난류가 교차하는 풍부한 어장으로, 대형 어종을 만날 수 있는 다이빙 포인트입니다.',
    descriptionEn: 'Located between Jeju and the mainland, Chujado sits at the crossroads of warm and cold currents, rich in big fish species.',
    highlights: ['한난류 교차 풍부한 어장', '대형 어종 서식', '낚시와 다이빙 명소'],
    highlightsEn: ['Rich fishery at current crossroads', 'Big fish habitat', 'Fishing and diving hotspot'],
    activityTypes: ['skin', 'scuba'],
  },
];
