// 전 세계 다이빙 스팟 데이터
export const REGIONS = [
  { id: 'korea', label: '한국' },
  { id: 'southeast-asia', label: '동남아시아' },
  { id: 'oceania', label: '오세아니아' },
  { id: 'indian-ocean', label: '인도양' },
  { id: 'red-sea', label: '홍해' },
  { id: 'caribbean', label: '카리브해' },
  { id: 'europe', label: '유럽' },
  { id: 'east-asia', label: '동아시아' },
  { id: 'pacific', label: '태평양' },
];

export const DIFFICULTIES = [
  { id: 'beginner', label: '초급', color: '#22c55e' },
  { id: 'intermediate', label: '중급', color: '#f59e0b' },
  { id: 'advanced', label: '상급', color: '#ef4444' },
];

export const spots = [
  // ── 한국 (7곳) ──
  {
    id: 1,
    name: '문섬',
    region: 'korea',
    country: '한국',
    lat: 33.2270,
    lng: 126.5650,
    depth: '5~40m',
    visibility: '10~30m',
    waterTemp: { min: 14, max: 26 },
    difficulty: 'intermediate',
    bestSeason: ['6월', '7월', '8월', '9월', '10월'],
    marineLife: ['연산호', '해마', '쏠배감펭', '넙치', '문어'],
    description: '제주도 서귀포 앞바다에 위치한 무인도로, 국내 최고의 연산호 군락지입니다. 화려한 수중 경관과 다양한 해양생물을 만날 수 있습니다.',
    highlights: ['국내 최대 연산호 군락', '수중 절벽 월다이빙', '다양한 난류성 어종'],
  },
  {
    id: 2,
    name: '우도',
    region: 'korea',
    country: '한국',
    lat: 33.5040,
    lng: 126.9520,
    depth: '5~25m',
    visibility: '8~20m',
    waterTemp: { min: 13, max: 25 },
    difficulty: 'beginner',
    bestSeason: ['6월', '7월', '8월', '9월'],
    marineLife: ['돌돔', '자리돔', '해삼', '성게', '소라'],
    description: '제주도 동쪽에 위치한 우도는 초보 다이버에게 적합한 완만한 수중 지형을 가지고 있으며, 맑은 물과 아름다운 백사장이 특징입니다.',
    highlights: ['초보자 친화적 포인트', '백사장 모래바닥', '완만한 수중 지형'],
  },
  {
    id: 3,
    name: '범섬',
    region: 'korea',
    country: '한국',
    lat: 33.2190,
    lng: 126.5160,
    depth: '10~45m',
    visibility: '10~25m',
    waterTemp: { min: 14, max: 26 },
    difficulty: 'advanced',
    bestSeason: ['6월', '7월', '8월', '9월', '10월'],
    marineLife: ['대형 연산호', '거북이', '쥐치', '방어', '참돔'],
    description: '서귀포 앞바다의 무인도로, 깊은 수심과 강한 조류가 특징인 상급자용 다이빙 사이트입니다. 대형 연산호와 다양한 대형 어종을 관찰할 수 있습니다.',
    highlights: ['딥다이빙 포인트', '강한 조류 드리프트', '대형 어종 출현'],
  },
  {
    id: 4,
    name: '울릉도',
    region: 'korea',
    country: '한국',
    lat: 37.4845,
    lng: 130.9057,
    depth: '5~35m',
    visibility: '15~30m',
    waterTemp: { min: 10, max: 24 },
    difficulty: 'intermediate',
    bestSeason: ['7월', '8월', '9월'],
    marineLife: ['대왕문어', '혹돔', '방어떼', '해조류', '불가사리'],
    description: '동해의 보석 울릉도는 깨끗한 수질과 높은 시야가 자랑입니다. 독특한 화산 지형의 수중 경관과 동해 특유의 해양생물을 만날 수 있습니다.',
    highlights: ['동해 최고 시야', '화산 지형 수중경관', '대왕문어 서식지'],
  },
  {
    id: 5,
    name: '거문도',
    region: 'korea',
    country: '한국',
    lat: 34.0280,
    lng: 127.3100,
    depth: '5~30m',
    visibility: '8~20m',
    waterTemp: { min: 14, max: 25 },
    difficulty: 'intermediate',
    bestSeason: ['6월', '7월', '8월', '9월'],
    marineLife: ['연산호', '갯민숭달팽이', '해마', '놀래기', '쥐노래미'],
    description: '전남 여수에 위치한 거문도는 다도해해상국립공원의 일부로, 풍부한 연산호와 다양한 매크로 생물이 특징입니다.',
    highlights: ['다도해 수중경관', '매크로 생물 천국', '연산호 군락'],
  },
  {
    id: 6,
    name: '독도',
    region: 'korea',
    country: '한국',
    lat: 37.2426,
    lng: 131.8597,
    depth: '10~40m',
    visibility: '15~30m',
    waterTemp: { min: 10, max: 23 },
    difficulty: 'advanced',
    bestSeason: ['7월', '8월', '9월'],
    marineLife: ['대형 해조류', '전복', '소라', '혹돔', '방어'],
    description: '대한민국 최동단 독도는 한류와 난류가 만나는 특수한 해역으로, 독특한 수중 생태계를 자랑합니다. 허가가 필요한 특별한 다이빙 사이트입니다.',
    highlights: ['대한민국 최동단 다이빙', '한난류 교차 해역', '특별 허가 필요'],
  },
  {
    id: 7,
    name: '서귀포 해양공원',
    region: 'korea',
    country: '한국',
    lat: 33.2400,
    lng: 126.5600,
    depth: '3~18m',
    visibility: '8~20m',
    waterTemp: { min: 15, max: 26 },
    difficulty: 'beginner',
    bestSeason: ['5월', '6월', '7월', '8월', '9월', '10월'],
    marineLife: ['열대어', '말미잘', '해삼', '불가사리', '자리돔'],
    description: '서귀포 해양공원은 다양한 수중 생물과 아름다운 산호를 감상할 수 있는 초보자 친화적인 다이빙 사이트입니다.',
    highlights: ['초보자 교육 최적', '얕은 수심', '접근성 우수'],
  },

  // ── 동남아시아 (8곳) ──
  {
    id: 8,
    name: '투바타하 리프',
    region: 'southeast-asia',
    country: '필리핀',
    lat: 8.9167,
    lng: 119.8333,
    depth: '5~40m',
    visibility: '30~45m',
    waterTemp: { min: 27, max: 30 },
    difficulty: 'intermediate',
    bestSeason: ['3월', '4월', '5월', '6월'],
    marineLife: ['만타레이', '상어', '거북이', '바라쿠다', '잭피쉬'],
    description: 'UNESCO 세계자연유산으로 지정된 투바타하 리프는 필리핀 최고의 다이빙 사이트로, 원시 그대로의 산호초와 대형 해양생물을 만날 수 있습니다.',
    highlights: ['UNESCO 세계자연유산', '원시 산호초', '대형 해양생물 집결지'],
  },
  {
    id: 9,
    name: '시밀란 제도',
    region: 'southeast-asia',
    country: '태국',
    lat: 8.6500,
    lng: 97.6500,
    depth: '5~35m',
    visibility: '20~40m',
    waterTemp: { min: 27, max: 30 },
    difficulty: 'beginner',
    bestSeason: ['11월', '12월', '1월', '2월', '3월', '4월'],
    marineLife: ['만타레이', '고래상어', '거북이', '레오파드상어', '리프피쉬'],
    description: '안다만 해에 위치한 시밀란 제도는 세계 10대 다이빙 사이트 중 하나로, 맑은 물과 다양한 대형 해양생물이 특징입니다.',
    highlights: ['세계 10대 다이빙 사이트', '만타레이 포인트', '크리스탈 클리어 시야'],
  },
  {
    id: 10,
    name: '코모도 국립공원',
    region: 'southeast-asia',
    country: '인도네시아',
    lat: -8.5500,
    lng: 119.4833,
    depth: '5~40m',
    visibility: '10~30m',
    waterTemp: { min: 24, max: 29 },
    difficulty: 'intermediate',
    bestSeason: ['4월', '5월', '6월', '7월', '8월', '9월', '10월', '11월'],
    marineLife: ['만타레이', '상어', '해마', '갑오징어', '산호'],
    description: '코모도 드래곤으로 유명한 이 국립공원은 수중에서도 놀라운 생물 다양성을 자랑합니다. 강한 조류가 풍부한 영양분을 공급합니다.',
    highlights: ['만타레이 클리닝 스테이션', '강한 조류 다이빙', '놀라운 생물 다양성'],
  },
  {
    id: 11,
    name: '시파단',
    region: 'southeast-asia',
    country: '말레이시아',
    lat: 4.1147,
    lng: 118.6292,
    depth: '5~40m',
    visibility: '20~40m',
    waterTemp: { min: 26, max: 30 },
    difficulty: 'intermediate',
    bestSeason: ['4월', '5월', '6월', '7월', '8월', '9월', '10월', '11월', '12월'],
    marineLife: ['거북이 떼', '바라쿠다 토네이도', '잭피쉬', '화이트팁상어', '범프헤드'],
    description: '자크 쿠스토가 "보지 않은 예술작품"이라 극찬한 시파단은 거대한 드롭오프와 함께 엄청난 수의 거북이와 물고기 떼를 볼 수 있습니다.',
    highlights: ['바라쿠다 토네이도', '거북이 떼 포인트', '600m 드롭오프 월'],
  },
  {
    id: 12,
    name: '블루코너 (팔라우)',
    region: 'southeast-asia',
    country: '팔라우',
    lat: 7.1167,
    lng: 134.2167,
    depth: '10~35m',
    visibility: '20~50m',
    waterTemp: { min: 27, max: 30 },
    difficulty: 'advanced',
    bestSeason: ['10월', '11월', '12월', '1월', '2월', '3월', '4월'],
    marineLife: ['그레이리프상어', '나폴레옹피쉬', '만타레이', '독수리가오리', '바라쿠다'],
    description: '세계 최고의 다이빙 포인트로 꼽히는 블루코너는 강한 조류와 함께 엄청난 수의 상어와 대형 어종을 볼 수 있는 드리프트 다이빙 사이트입니다.',
    highlights: ['세계 최고 월다이빙', '상어 군무', '후크 다이빙 체험'],
  },
  {
    id: 13,
    name: '라자 암팟',
    region: 'southeast-asia',
    country: '인도네시아',
    lat: -0.2333,
    lng: 130.5167,
    depth: '5~30m',
    visibility: '10~30m',
    waterTemp: { min: 27, max: 30 },
    difficulty: 'beginner',
    bestSeason: ['10월', '11월', '12월', '1월', '2월', '3월', '4월'],
    marineLife: ['만타레이', '워비공상어', '피그미해마', '누디브랜치', '산호'],
    description: '지구상 해양 생물 다양성이 가장 높은 지역으로, 1,500종 이상의 물고기와 600종 이상의 산호가 서식합니다.',
    highlights: ['지구 최고 생물다양성', '워비공상어 서식지', '원시 산호초'],
  },
  {
    id: 14,
    name: '엘니도',
    region: 'southeast-asia',
    country: '필리핀',
    lat: 11.1784,
    lng: 119.3930,
    depth: '5~30m',
    visibility: '10~25m',
    waterTemp: { min: 26, max: 30 },
    difficulty: 'beginner',
    bestSeason: ['11월', '12월', '1월', '2월', '3월', '4월', '5월'],
    marineLife: ['거북이', '리프피쉬', '넙치', '누디브랜치', '산호'],
    description: '석회암 절벽으로 둘러싸인 엘니도는 아름다운 수중 경관과 함께 다양한 해양생물을 만날 수 있는 초보자 친화적 다이빙 사이트입니다.',
    highlights: ['석회암 절벽 수중경관', '거북이 스노클링', '초보자 추천'],
  },
  {
    id: 15,
    name: '리슐리외 락',
    region: 'southeast-asia',
    country: '태국',
    lat: 9.3667,
    lng: 98.0167,
    depth: '5~35m',
    visibility: '15~35m',
    waterTemp: { min: 27, max: 30 },
    difficulty: 'intermediate',
    bestSeason: ['11월', '12월', '1월', '2월', '3월', '4월'],
    marineLife: ['고래상어', '만타레이', '해마', '하를레퀸쉬림프', '보라색 산호'],
    description: '태국 최고의 다이빙 사이트로, 보라색 연산호로 뒤덮인 수중 피나클이 장관입니다. 고래상어와의 만남도 기대할 수 있습니다.',
    highlights: ['고래상어 출현 포인트', '보라색 연산호 군락', '매크로 사진 최적'],
  },

  // ── 오세아니아 (4곳) ──
  {
    id: 16,
    name: '그레이트 배리어 리프',
    region: 'oceania',
    country: '호주',
    lat: -18.2861,
    lng: 147.7000,
    depth: '5~30m',
    visibility: '15~30m',
    waterTemp: { min: 22, max: 29 },
    difficulty: 'beginner',
    bestSeason: ['6월', '7월', '8월', '9월', '10월', '11월'],
    marineLife: ['거북이', '클라운피쉬', '만타레이', '드워프밍크고래', '리프상어'],
    description: '세계 최대의 산호초 지대로, 2,300km에 걸쳐 펼쳐진 거대한 생태계입니다. 드워프밍크고래와의 특별한 만남도 가능합니다.',
    highlights: ['세계 최대 산호초', '드워프밍크고래 스윔', 'UNESCO 세계유산'],
  },
  {
    id: 17,
    name: '보라보라',
    region: 'oceania',
    country: '프랑스령 폴리네시아',
    lat: -16.5004,
    lng: -151.7415,
    depth: '5~30m',
    visibility: '20~40m',
    waterTemp: { min: 25, max: 29 },
    difficulty: 'beginner',
    bestSeason: ['5월', '6월', '7월', '8월', '9월', '10월', '11월'],
    marineLife: ['블랙팁상어', '레몬상어', '만타레이', '거북이', '독수리가오리'],
    description: '에메랄드빛 라군으로 유명한 보라보라는 상어와 가오리와 함께 하는 편안한 다이빙을 즐길 수 있습니다.',
    highlights: ['상어 피딩 다이빙', '에메랄드 라군', '가오리 포인트'],
  },
  {
    id: 18,
    name: '푸어나이츠 제도',
    region: 'oceania',
    country: '뉴질랜드',
    lat: -35.4800,
    lng: 174.7400,
    depth: '10~40m',
    visibility: '15~30m',
    waterTemp: { min: 14, max: 22 },
    difficulty: 'intermediate',
    bestSeason: ['1월', '2월', '3월', '4월', '5월'],
    marineLife: ['쏠배감펭', '킹피쉬', '누디브랜치', '해면', '가오리'],
    description: '쿠스토가 세계 10대 다이빙 사이트로 선정한 푸어나이츠는 아치, 동굴, 터널 등 다양한 수중 지형이 특징입니다.',
    highlights: ['수중 아치와 동굴', '자크 쿠스토 선정', '켈프 숲 다이빙'],
  },
  {
    id: 19,
    name: '피지 소모소모 해협',
    region: 'oceania',
    country: '피지',
    lat: -16.8000,
    lng: 179.9833,
    depth: '5~40m',
    visibility: '15~30m',
    waterTemp: { min: 25, max: 29 },
    difficulty: 'intermediate',
    bestSeason: ['4월', '5월', '6월', '7월', '8월', '9월', '10월'],
    marineLife: ['불상어', '화이트팁상어', '연산호', '바라쿠다', '만타레이'],
    description: '세계 연산호 수도로 불리는 피지의 소모소모 해협은 화려한 연산호와 상어 다이빙으로 유명합니다.',
    highlights: ['세계 연산호 수도', '상어 다이빙', '강한 조류 드리프트'],
  },

  // ── 인도양 (4곳) ──
  {
    id: 20,
    name: '몰디브 아리환초',
    region: 'indian-ocean',
    country: '몰디브',
    lat: 3.8500,
    lng: 72.8500,
    depth: '5~35m',
    visibility: '20~40m',
    waterTemp: { min: 27, max: 30 },
    difficulty: 'beginner',
    bestSeason: ['1월', '2월', '3월', '4월', '11월', '12월'],
    marineLife: ['고래상어', '만타레이', '거북이', '모레이일', '리프상어'],
    description: '몰디브 최고의 다이빙 환초로, 고래상어와 만타레이를 가장 높은 확률로 만날 수 있습니다. 크리스탈처럼 맑은 물이 특징입니다.',
    highlights: ['고래상어 보장 포인트', '만타레이 클리닝 스테이션', '오버행 다이빙'],
  },
  {
    id: 21,
    name: '세이셸',
    region: 'indian-ocean',
    country: '세이셸',
    lat: -4.6796,
    lng: 55.4920,
    depth: '5~30m',
    visibility: '15~30m',
    waterTemp: { min: 26, max: 30 },
    difficulty: 'beginner',
    bestSeason: ['3월', '4월', '5월', '10월', '11월'],
    marineLife: ['거북이', '독수리가오리', '고래상어', '리프피쉬', '넙치'],
    description: '인도양의 낙원 세이셸은 화강암 바위가 만들어내는 독특한 수중 지형과 풍부한 해양생물이 특징입니다.',
    highlights: ['화강암 수중 지형', '거북이 보호구역', '투명한 라군'],
  },
  {
    id: 22,
    name: '잔지바르',
    region: 'indian-ocean',
    country: '탄자니아',
    lat: -6.1659,
    lng: 39.1989,
    depth: '5~30m',
    visibility: '15~25m',
    waterTemp: { min: 25, max: 29 },
    difficulty: 'beginner',
    bestSeason: ['10월', '11월', '12월', '1월', '2월', '3월'],
    marineLife: ['돌고래', '거북이', '리프피쉬', '문어', '가오리'],
    description: '아프리카 동해안의 잔지바르는 돌고래와 함께 수영하며 다이빙을 즐길 수 있는 특별한 곳입니다.',
    highlights: ['돌고래 스윔', '스파이스 아일랜드', '산호정원'],
  },
  {
    id: 23,
    name: '레위니옹',
    region: 'indian-ocean',
    country: '프랑스령 레위니옹',
    lat: -21.1151,
    lng: 55.5364,
    depth: '10~40m',
    visibility: '10~25m',
    waterTemp: { min: 22, max: 28 },
    difficulty: 'intermediate',
    bestSeason: ['10월', '11월', '12월', '1월', '2월', '3월'],
    marineLife: ['혹등고래', '거북이', '돌고래', '바라쿠다', '리프피쉬'],
    description: '화산섬 레위니옹은 용암이 만들어낸 독특한 수중 지형과 혹등고래 시즌의 특별한 만남이 가능한 곳입니다.',
    highlights: ['혹등고래 시즌(7~10월)', '화산 수중지형', '난파선 다이빙'],
  },

  // ── 홍해 (4곳) ──
  {
    id: 24,
    name: '라스 모하메드',
    region: 'red-sea',
    country: '이집트',
    lat: 27.7347,
    lng: 34.2534,
    depth: '5~40m',
    visibility: '20~40m',
    waterTemp: { min: 21, max: 28 },
    difficulty: 'intermediate',
    bestSeason: ['3월', '4월', '5월', '6월', '9월', '10월', '11월'],
    marineLife: ['잭피쉬 토네이도', '바라쿠다', '나폴레옹피쉬', '상어', '거북이'],
    description: '시나이 반도 끝에 위치한 라스 모하메드는 홍해 최고의 다이빙 사이트로, 웅장한 드롭오프와 거대한 물고기 떼가 장관입니다.',
    highlights: ['샤크 리프 & 요란다 리프', '잭피쉬 월', '맑은 시야'],
  },
  {
    id: 25,
    name: 'SS 시슬곰 난파선',
    region: 'red-sea',
    country: '이집트',
    lat: 27.8619,
    lng: 34.3061,
    depth: '15~30m',
    visibility: '15~30m',
    waterTemp: { min: 21, max: 28 },
    difficulty: 'intermediate',
    bestSeason: ['3월', '4월', '5월', '9월', '10월', '11월'],
    marineLife: ['라이온피쉬', '글래스피쉬', '모레이일', '바라쿠다', '리프피쉬'],
    description: '1941년 독일 폭격으로 침몰한 영국 화물선으로, 세계에서 가장 유명한 난파선 다이빙 포인트 중 하나입니다.',
    highlights: ['세계 최고 난파선 다이빙', '역사적 화물선', '풍부한 해양생물'],
  },
  {
    id: 26,
    name: '다합',
    region: 'red-sea',
    country: '이집트',
    lat: 28.4913,
    lng: 34.5131,
    depth: '5~100m+',
    visibility: '20~40m',
    waterTemp: { min: 21, max: 28 },
    difficulty: 'beginner',
    bestSeason: ['3월', '4월', '5월', '9월', '10월', '11월'],
    marineLife: ['블루홀 원양어류', '거북이', '리프피쉬', '산호', '라이온피쉬'],
    description: '세계적으로 유명한 블루홀이 있는 다합은 프리다이버와 스쿠버다이버 모두에게 사랑받는 곳입니다. 해안 다이빙이 가능합니다.',
    highlights: ['블루홀 (깊이 100m+)', '해안 진입 다이빙', '프리다이빙 성지'],
  },
  {
    id: 27,
    name: '브라더스 제도',
    region: 'red-sea',
    country: '이집트',
    lat: 26.3200,
    lng: 34.8500,
    depth: '10~60m+',
    visibility: '20~40m',
    waterTemp: { min: 22, max: 28 },
    difficulty: 'advanced',
    bestSeason: ['5월', '6월', '7월', '9월', '10월', '11월'],
    marineLife: ['귀상어 떼', '화이트팁상어', '만타레이', '나폴레옹피쉬', '참치'],
    description: '홍해 한가운데 위치한 외딴 섬으로, 리브어보드로만 접근 가능합니다. 귀상어 떼와 대형 상어를 만날 수 있는 홍해 최고의 상어 포인트입니다.',
    highlights: ['귀상어 떼', '리브어보드 전용', '홍해 최고 상어 포인트'],
  },

  // ── 카리브해 (4곳) ──
  {
    id: 28,
    name: '코수멜',
    region: 'caribbean',
    country: '멕시코',
    lat: 20.4318,
    lng: -86.9203,
    depth: '5~35m',
    visibility: '20~40m',
    waterTemp: { min: 25, max: 29 },
    difficulty: 'beginner',
    bestSeason: ['3월', '4월', '5월', '6월', '11월', '12월'],
    marineLife: ['거북이', '간호사상어', '독수리가오리', '스플렌디드토드피쉬', '산호'],
    description: '멕시코 카리브해의 코수멜은 세계적으로 유명한 드리프트 다이빙 사이트로, 편안한 조류를 타며 아름다운 산호 월을 감상할 수 있습니다.',
    highlights: ['편안한 드리프트 다이빙', '산호 월 다이빙', '스플렌디드토드피쉬'],
  },
  {
    id: 29,
    name: '벨리즈 블루홀',
    region: 'caribbean',
    country: '벨리즈',
    lat: 17.3155,
    lng: -87.5347,
    depth: '40~130m',
    visibility: '30~60m',
    waterTemp: { min: 26, max: 29 },
    difficulty: 'advanced',
    bestSeason: ['4월', '5월', '6월'],
    marineLife: ['리프상어', '불상어', '거대 종유석', '바라쿠다', '엔젤피쉬'],
    description: '직경 300m, 깊이 130m의 거대한 싱크홀은 세계에서 가장 유명한 다이빙 사이트 중 하나입니다. 수중 종유석이 장관입니다.',
    highlights: ['세계 최대 블루홀', '수중 종유석', '항공 촬영 명소'],
  },
  {
    id: 30,
    name: '보네르',
    region: 'caribbean',
    country: '네덜란드령 안틸레스',
    lat: 12.1443,
    lng: -68.2655,
    depth: '5~40m',
    visibility: '20~40m',
    waterTemp: { min: 26, max: 29 },
    difficulty: 'beginner',
    bestSeason: ['1월', '2월', '3월', '4월', '5월', '6월', '7월', '8월', '9월', '10월', '11월', '12월'],
    marineLife: ['해마', '거북이', '리프피쉬', '문어', '해면'],
    description: '다이버의 천국 보네르는 해안에서 직접 입수할 수 있는 80개 이상의 다이빙 사이트를 보유하고 있습니다. 연중 다이빙이 가능합니다.',
    highlights: ['해안 진입 다이빙', '연중 다이빙 가능', '80+ 다이빙 사이트'],
  },
  {
    id: 31,
    name: '케이맨 제도',
    region: 'caribbean',
    country: '케이맨 제도',
    lat: 19.3133,
    lng: -81.2546,
    depth: '5~40m',
    visibility: '25~40m',
    waterTemp: { min: 26, max: 29 },
    difficulty: 'beginner',
    bestSeason: ['3월', '4월', '5월', '6월', '11월', '12월'],
    marineLife: ['가오리', '거북이', '리프상어', '타폰', '엔젤피쉬'],
    description: '스팅레이 시티로 유명한 케이맨 제도는 가오리와 직접 교감할 수 있는 특별한 경험을 제공합니다.',
    highlights: ['스팅레이 시티', '키트윙키 난파선', '월 다이빙'],
  },

  // ── 유럽 (4곳) ──
  {
    id: 32,
    name: '아조레스 제도',
    region: 'europe',
    country: '포르투갈',
    lat: 37.7833,
    lng: -25.5000,
    depth: '10~40m',
    visibility: '15~40m',
    waterTemp: { min: 16, max: 24 },
    difficulty: 'intermediate',
    bestSeason: ['6월', '7월', '8월', '9월', '10월'],
    marineLife: ['블루상어', '모불라가오리', '돌고래', '향유고래', '참치'],
    description: '대서양 한가운데 위치한 아조레스는 대형 원양어류와의 만남이 보장되는 유럽 최고의 다이빙 목적지입니다.',
    highlights: ['블루상어 다이빙', '향유고래 스윔', '대서양 원양어류'],
  },
  {
    id: 33,
    name: '몰타 블루홀',
    region: 'europe',
    country: '몰타',
    lat: 36.0566,
    lng: 14.2130,
    depth: '5~35m',
    visibility: '20~40m',
    waterTemp: { min: 15, max: 27 },
    difficulty: 'beginner',
    bestSeason: ['5월', '6월', '7월', '8월', '9월', '10월'],
    marineLife: ['문어', '바라쿠다', '앰버잭', '뱀장어', '해면'],
    description: '고조 섬의 블루홀은 자연이 만들어낸 수중 아치와 동굴로 유명하며, 유럽에서 가장 아름다운 다이빙 사이트 중 하나입니다.',
    highlights: ['천연 수중 아치', '아주르 윈도우', '해안 진입 다이빙'],
  },
  {
    id: 34,
    name: '크로아티아 비스섬',
    region: 'europe',
    country: '크로아티아',
    lat: 43.0600,
    lng: 16.1900,
    depth: '5~50m',
    visibility: '20~40m',
    waterTemp: { min: 13, max: 25 },
    difficulty: 'intermediate',
    bestSeason: ['5월', '6월', '7월', '8월', '9월', '10월'],
    marineLife: ['문어', '바라쿠다', '참돔', '로브스터', '해면'],
    description: '아드리아해의 숨겨진 보석 비스섬은 2차 세계대전 난파선과 수중 동굴 다이빙이 가능한 유럽의 인기 다이빙 사이트입니다.',
    highlights: ['2차대전 난파선', '블루 동굴', '아드리아해 투명한 물'],
  },
  {
    id: 35,
    name: '노르웨이 로포텐',
    region: 'europe',
    country: '노르웨이',
    lat: 68.2000,
    lng: 14.4000,
    depth: '5~30m',
    visibility: '10~25m',
    waterTemp: { min: 4, max: 14 },
    difficulty: 'advanced',
    bestSeason: ['1월', '2월', '3월', '9월', '10월'],
    marineLife: ['범고래', '대구', '킹크랩', '해조류', '해삼'],
    description: '북극권에 위치한 로포텐은 범고래와 함께 다이빙할 수 있는 세계에서 몇 안 되는 곳 중 하나입니다. 오로라 시즌에는 환상적인 야간 다이빙도 가능합니다.',
    highlights: ['범고래 다이빙', '오로라 나이트다이빙', '북극권 콜드워터'],
  },

  // ── 동아시아 (2곳) ──
  {
    id: 36,
    name: '오키나와 게라마 제도',
    region: 'east-asia',
    country: '일본',
    lat: 26.1900,
    lng: 127.3000,
    depth: '5~35m',
    visibility: '20~40m',
    waterTemp: { min: 21, max: 29 },
    difficulty: 'beginner',
    bestSeason: ['4월', '5월', '6월', '7월', '8월', '9월', '10월'],
    marineLife: ['만타레이', '거북이', '클라운피쉬', '산호', '해마'],
    description: '오키나와의 게라마 제도는 "케라마 블루"로 불리는 투명한 바다와 만타레이 포인트로 유명합니다.',
    highlights: ['케라마 블루', '만타레이 포인트', '거북이 서식지'],
  },
  {
    id: 37,
    name: '란위 (대만)',
    region: 'east-asia',
    country: '대만',
    lat: 22.0500,
    lng: 121.5500,
    depth: '5~30m',
    visibility: '20~40m',
    waterTemp: { min: 23, max: 29 },
    difficulty: 'beginner',
    bestSeason: ['4월', '5월', '6월', '7월', '8월', '9월', '10월'],
    marineLife: ['플라잉피쉬', '클라운피쉬', '거북이', '산호', '리프피쉬'],
    description: '대만 동남쪽의 란위(난유)는 원주민 타오족의 독특한 문화와 함께 아름다운 수중 세계를 경험할 수 있는 곳입니다.',
    highlights: ['플라잉피쉬 시즌', '원주민 타오 문화', '화산섬 다이빙'],
  },

  // ── 태평양 (1곳) ──
  {
    id: 38,
    name: '갈라파고스',
    region: 'pacific',
    country: '에콰도르',
    lat: -0.9538,
    lng: -90.9656,
    depth: '10~40m',
    visibility: '10~25m',
    waterTemp: { min: 16, max: 26 },
    difficulty: 'advanced',
    bestSeason: ['6월', '7월', '8월', '9월', '10월', '11월'],
    marineLife: ['귀상어 수백마리', '고래상어', '바다이구아나', '물개', '만타레이'],
    description: '다윈의 진화론이 탄생한 갈라파고스는 수백 마리의 귀상어 떼와 바다이구아나 등 이곳에서만 볼 수 있는 생물들로 가득합니다.',
    highlights: ['귀상어 수백마리 군무', '바다이구아나', '다윈의 섬'],
  },
];
